unit SfmlGraphics;

////////////////////////////////////////////////////////////
//
// PasSFML - Simple and Fast Multimedia Library for Pascal
// Copyright (C) 2015 Christian-W. Budde (Christian@savioursofsoul.de)
//
// This software is provided 'as-is', without any express or implied warranty.
// In no event will the authors be held liable for any damages arising from the use of this software.
//
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it freely,
// subject to the following restrictions:
//
// 1. The origin of this software must not be misrepresented;
//    you must not claim that you wrote the original software.
//    If you use this software in a product, an acknowledgment
//    in the product documentation would be appreciated but is not required.
//
// 2. Altered source versions must be plainly marked as such,
//    and must not be misrepresented as being the original software.
//
// 3. This notice may not be removed or altered from any source distribution.
//
////////////////////////////////////////////////////////////

interface

{$I Sfml.inc}

uses
  {$IFDEF MSWindows}Windows, {$ENDIF} SfmlWindow, SfmlSystem;

type
  PSfmlCircleShape = Pointer;
  PSfmlConvexShape = Pointer;
  PSfmlFont = Pointer;
  PSfmlImage = Pointer;
  PSfmlShader = Pointer;
  PSfmlRectangleShape = Pointer;
  PSfmlRenderTexture = Pointer;
  PSfmlRenderWindow = Pointer;
  PSfmlShape = Pointer;
  PSfmlSprite = Pointer;
  PSfmlText = Pointer;
  PSfmlTexture = Pointer;
  PSfmlTransformable = Pointer;
  PSfmlVertexArray = Pointer;
  PSfmlView = Pointer;

  TSfmlBlendFactor = (sfBlendFactorZero, sfBlendFactorOne,
    sfBlendFactorSrcColor, sfBlendFactorOneMinusSrcColor,
    sfBlendFactorDstColor, sfBlendFactorOneMinusDstColor,
    sfBlendFactorSrcAlpha, sfBlendFactorOneMinusSrcAlpha,
    sfBlendFactorDstAlpha, sfBlendFactorOneMinusDstAlpha);

  TSfmlBlendEquation = (sfBlendEquationAdd, sfBlendEquationSubtract);

  TSfmlBlendMode = record
    colorSrcFactor: TSfmlBlendFactor;
    colorDstFactor: TSfmlBlendFactor;
    colorEquation: TSfmlBlendEquation;
    alphaSrcFactor: TSfmlBlendFactor;
    alphaDstFactor: TSfmlBlendFactor;
    alphaEquation: TSfmlBlendEquation;
  end;

  TSfmlColor = packed record
    r, g, b, a: sfUint8;
  end;

  TSfmlFontInfo = record
    Family: PAnsiChar;
  end;

  TSfmlFloatRect = record
    Left, Top, Width, Height: Single;
  end;

  TSfmlIntRect = record
    Left, Top, Width, Height: longint;
  end;
  PSfmlIntRect = ^TSfmlIntRect;

  TSfmlGlyph = record
    Advance: Single;
    Bounds: TSfmlFloatRect;
    TextureRect: TSfmlIntRect;
  end;

  TSfmlPrimitiveType = (sfPoints, sfLines, sfLinesStrip, sfTriangles,
    sfTrianglesStrip, sfTrianglesFan, sfQuads);

  TSfmlTransform = record
    Matrix : array [0 .. 8] of Single;
  end;
  PSfmlTransform = ^TSfmlTransform;

  TSfmlRenderStates = record
    BlendMode: TSfmlBlendMode;
    Transform: TSfmlTransform;
    Texture: PSfmlTexture;
    Shader: PSfmlShader;
  end;
  PSfmlRenderStates = ^TSfmlRenderStates;

  TSfmlShapeGetPointCountCallback = function (Para1: Pointer): Cardinal; cdecl;
  TSfmlShapeGetPointCallback = function (Para1: Cardinal; Para2: Pointer): TSfmlVector2f; cdecl;

  TSfmlTextStyle = (sfTextBold, sfTextItalic, sfTextUnderlined,
    sfTextStrikeThrough);
  TSfmlTextStyles = set of TSfmlTextStyle;

  TSfmlVertex = record
    Position: TSfmlVector2f;
    Color: TSfmlColor;
    TexCoords: TSfmlVector2f;
  end;
  PSfmlVertex = ^TSfmlVertex;

  TSfmlBlendAlpha = function : TSfmlBlendMode; cdecl;
  TSfmlBlendAdd = function : TSfmlBlendMode; cdecl;
  TSfmlBlendMultiply = function : TSfmlBlendMode; cdecl;
  TSfmlBlendNone = function : TSfmlBlendMode; cdecl;

  TSfmlColorFromRGB = function (Red, Green, Blue: sfUint8): TSfmlColor; cdecl;
  TSfmlColorFromRGBA = function (Red, Green, Blue, Alpha: sfUint8): TSfmlColor; cdecl;
  TSfmlColorAdd = function (color1, color2: TSfmlColor): TSfmlColor; cdecl;
  TSfmlColorModulate = function (color1, color2: TSfmlColor): TSfmlColor; cdecl;

  TSfmlCircleShapeCreate = function : PSfmlCircleShape; cdecl;
  TSfmlCircleShapeCopy = function (const Shape: PSfmlCircleShape): PSfmlCircleShape; cdecl;
  TSfmlCircleShapeDestroy = procedure (Shape: PSfmlCircleShape); cdecl;
  TSfmlCircleShapeSetPosition = procedure (Shape: PSfmlCircleShape; Position: TSfmlVector2f); cdecl;
  TSfmlCircleShapeSetRotation = procedure (Shape: PSfmlCircleShape; Angle: Single); cdecl;
  TSfmlCircleShapeSetScale = procedure (Shape: PSfmlCircleShape; Scale: TSfmlVector2f); cdecl;
  TSfmlCircleShapeSetOrigin = procedure (Shape: PSfmlCircleShape; Origin: TSfmlVector2f); cdecl;
  TSfmlCircleShapeGetPosition = function (const Shape: PSfmlCircleShape): TSfmlVector2f; cdecl;
  TSfmlCircleShapeGetRotation = function (const Shape: PSfmlCircleShape): Single; cdecl;
  TSfmlCircleShapeGetScale = function (const Shape: PSfmlCircleShape): TSfmlVector2f; cdecl;
  TSfmlCircleShapeGetOrigin = function (const Shape: PSfmlCircleShape): TSfmlVector2f; cdecl;
  TSfmlCircleShapeMove = procedure (Shape: PSfmlCircleShape; Offset: TSfmlVector2f); cdecl;
  TSfmlCircleShapeRotate = procedure (Shape: PSfmlCircleShape; Angle: Single); cdecl;
  TSfmlCircleShapeScale = procedure (Shape: PSfmlCircleShape; Factors: TSfmlVector2f); cdecl;
  TSfmlCircleShapeGetTransform = function (const Shape: PSfmlCircleShape): TSfmlTransform; cdecl;
  TSfmlCircleShapeGetInverseTransform = function (const Shape: PSfmlCircleShape): TSfmlTransform; cdecl;
  TSfmlCircleShapeSetTexture = procedure (Shape: PSfmlCircleShape; const Texture: PSfmlTexture; resetRect: sfBool); cdecl;
  TSfmlCircleShapeSetTextureRect = procedure (Shape: PSfmlCircleShape; Rect: TSfmlIntRect); cdecl;
  TSfmlCircleShapeSetFillColor = procedure (Shape: PSfmlCircleShape; Color: TSfmlColor); cdecl;
  TSfmlCircleShapeSetOutlineColor = procedure (Shape: PSfmlCircleShape; Color: TSfmlColor); cdecl;
  TSfmlCircleShapeSetOutlineThickness = procedure (Shape: PSfmlCircleShape; Thickness: Single); cdecl;
  TSfmlCircleShapeGetTexture = function (const Shape: PSfmlCircleShape): PSfmlTexture; cdecl;
  TSfmlCircleShapeGetTextureRect = function (const Shape: PSfmlCircleShape): TSfmlIntRect; cdecl;
  TSfmlCircleShapeGetFillColor = function (const Shape: PSfmlCircleShape): TSfmlColor; cdecl;
  TSfmlCircleShapeGetOutlineColor = function (const Shape: PSfmlCircleShape): TSfmlColor; cdecl;
  TSfmlCircleShapeGetOutlineThickness = function (const Shape: PSfmlCircleShape): Single; cdecl;
  TSfmlCircleShapeGetPointCount = function (const Shape: PSfmlCircleShape): Cardinal; cdecl;
  TSfmlCircleShapeGetPoint = function (const Shape: PSfmlCircleShape; Index: Cardinal): TSfmlVector2f; cdecl;
  TSfmlCircleShapeSetRadius = procedure (Shape: PSfmlCircleShape; Radius: Single); cdecl;
  TSfmlCircleShapeGetRadius = function (const Shape: PSfmlCircleShape): Single; cdecl;
  TSfmlCircleShapeSetPointCount = procedure (Shape: PSfmlCircleShape; Count: Cardinal); cdecl;
  TSfmlCircleShapeGetLocalBounds = function (const Shape: PSfmlCircleShape): TSfmlFloatRect; cdecl;
  TSfmlCircleShapeGetGlobalBounds = function (const Shape: PSfmlCircleShape): TSfmlFloatRect; cdecl;

  TSfmlConvexShapeCreate = function : PSfmlConvexShape; cdecl;
  TSfmlConvexShapeCopy = function (const Shape: PSfmlConvexShape): PSfmlConvexShape; cdecl;
  TSfmlConvexShapeDestroy = procedure (Shape: PSfmlConvexShape); cdecl;
  TSfmlConvexShapeSetPosition = procedure (Shape: PSfmlConvexShape; Position: TSfmlVector2f); cdecl;
  TSfmlConvexShapeSetRotation = procedure (Shape: PSfmlConvexShape; Angle: Single); cdecl;
  TSfmlConvexShapeSetScale = procedure (Shape: PSfmlConvexShape; Scale: TSfmlVector2f); cdecl;
  TSfmlConvexShapeSetOrigin = procedure (Shape: PSfmlConvexShape; Origin: TSfmlVector2f); cdecl;
  TSfmlConvexShapeGetPosition = function (const Shape: PSfmlConvexShape): TSfmlVector2f; cdecl;
  TSfmlConvexShapeGetRotation = function (const Shape: PSfmlConvexShape): Single; cdecl;
  TSfmlConvexShapeGetScale = function (const Shape: PSfmlConvexShape): TSfmlVector2f; cdecl;
  TSfmlConvexShapeGetOrigin = function (const Shape: PSfmlConvexShape): TSfmlVector2f; cdecl;
  TSfmlConvexShapeMove = procedure (Shape: PSfmlConvexShape; Offset: TSfmlVector2f); cdecl;
  TSfmlConvexShapeRotate = procedure (Shape: PSfmlConvexShape; Angle: Single); cdecl;
  TSfmlConvexShapeScale = procedure (Shape: PSfmlConvexShape; Factors: TSfmlVector2f); cdecl;
  TSfmlConvexShapeGetTransform = function (const Shape: PSfmlConvexShape): TSfmlTransform; cdecl;
  TSfmlConvexShapeGetInverseTransform = function (const Shape: PSfmlConvexShape): TSfmlTransform; cdecl;
  TSfmlConvexShapeSetTexture = procedure (Shape: PSfmlConvexShape; const Texture: PSfmlTexture; ResetRect: sfBool); cdecl;
  TSfmlConvexShapeSetTextureRect = procedure (Shape: PSfmlConvexShape; Rect: TSfmlIntRect); cdecl;
  TSfmlConvexShapeSetFillColor = procedure (Shape: PSfmlConvexShape; Color: TSfmlColor); cdecl;
  TSfmlConvexShapeSetOutlineColor = procedure (Shape: PSfmlConvexShape; Color: TSfmlColor); cdecl;
  TSfmlConvexShapeSetOutlineThickness = procedure (Shape: PSfmlConvexShape; Thickness: Single); cdecl;
  TSfmlConvexShapeGetTexture = function (const Shape: PSfmlConvexShape): PSfmlTexture; cdecl;
  TSfmlConvexShapeGetTextureRect = function (const Shape: PSfmlConvexShape): TSfmlIntRect; cdecl;
  TSfmlConvexShapeGetFillColor = function (const Shape: PSfmlConvexShape): TSfmlColor; cdecl;
  TSfmlConvexShapeGetOutlineColor = function (const Shape: PSfmlConvexShape): TSfmlColor; cdecl;
  TSfmlConvexShapeGetOutlineThickness = function (const Shape: PSfmlConvexShape): Single; cdecl;
  TSfmlConvexShapeGetPointCount = function (const Shape: PSfmlConvexShape): Cardinal; cdecl;
  TSfmlConvexShapeGetPoint = function (const Shape: PSfmlConvexShape; Index: Cardinal): TSfmlVector2f; cdecl;
  TSfmlConvexShapeSetPointCount = procedure (Shape: PSfmlConvexShape; Count: Cardinal); cdecl;
  TSfmlConvexShapeSetPoint = procedure (Shape: PSfmlConvexShape; Index: Cardinal; Point: TSfmlVector2f); cdecl;
  TSfmlConvexShapeGetLocalBounds = function (const Shape: PSfmlConvexShape): TSfmlFloatRect; cdecl;
  TSfmlConvexShapeGetGlobalBounds = function (const Shape: PSfmlConvexShape): TSfmlFloatRect; cdecl;

  TSfmlFontCreateFromFile = function (const FileName: PAnsiChar): PSfmlFont; cdecl;
  TSfmlFontCreateFromMemory = function (const Data: Pointer; SizeInBytes: NativeUInt): PSfmlFont; cdecl;
  TSfmlFontCreateFromStream = function (const Stream: PSfmlInputStream): PSfmlFont; cdecl;
  TSfmlFontCopy = function (const Font: PSfmlFont): PSfmlFont; cdecl;
  TSfmlFontDestroy = procedure (Font: PSfmlFont); cdecl;
  TSfmlFontGetGlyph = function (Font: PSfmlFont; CodePoint: sfUint32; CharacterSize: Cardinal; Bold: sfBool): TSfmlGlyph; cdecl;
  TSfmlFontGetKerning = function (Font: PSfmlFont; First, second: sfUint32; CharacterSize: Cardinal): Single; cdecl;
  TSfmlFontGetLineSpacing = function (Font: PSfmlFont; CharacterSize: Cardinal): Single; cdecl;
  TSfmlFontGetUnderlinePosition = function (Font: PSfmlFont; CharacterSize: Cardinal): Single; cdecl;
  TSfmlFontGetUnderlineThickness = function (Font: PSfmlFont; CharacterSize: Cardinal): Single; cdecl;
  TSfmlFontGetTexture = function (Font: PSfmlFont; CharacterSize: Cardinal): PSfmlTexture; cdecl;
  TSfmlFontGetInfo = function (const Font: PSfmlFont): TSfmlFontInfo; cdecl;

  TSfmlImageCreate = function (Width, Height: Cardinal): PSfmlImage; cdecl;
  TSfmlImageCreateFromColor = function (Width, Height: Cardinal; Color: TSfmlColor): PSfmlImage; cdecl;
  TSfmlImageCreateFromPixels = function (Width, Height: Cardinal; const Pixels: PByte): PSfmlImage; cdecl;
  TSfmlImageCreateFromFile = function (const FileName: PAnsiChar): PSfmlImage; cdecl;
  TSfmlImageCreateFromMemory = function (const data: Pointer; Size: NativeUInt): PSfmlImage; cdecl;
  TSfmlImageCreateFromStream = function (const Stream: PSfmlInputStream): PSfmlImage; cdecl;
  TSfmlImageCopy = function (const Image: PSfmlImage): PSfmlImage; cdecl;
  TSfmlImageDestroy = procedure (Image: PSfmlImage); cdecl;
  TSfmlImageSaveToFile = function (const Image: PSfmlImage; const FileName: PAnsiChar): sfBool; cdecl;
  TSfmlImageGetSize = function (const Image: PSfmlImage): TSfmlVector2u; cdecl;
  TSfmlImageCreateMaskFromColor = procedure (Image: PSfmlImage; Color: TSfmlColor; Alpha: sfUint8); cdecl;
  TSfmlImageCopyImage = procedure (Image: PSfmlImage; const source: PSfmlImage; destX, destY: Cardinal; sourceRect: TSfmlIntRect; applyAlpha: sfBool); cdecl;
  TSfmlImageSetPixel = procedure (Image: PSfmlImage; X, Y: Cardinal; Color: TSfmlColor); cdecl;
  TSfmlImageGetPixel = function (const Image: PSfmlImage; X, Y: Cardinal): TSfmlColor; cdecl;
  TSfmlImageGetPixelsPtr = function (const Image: PSfmlImage): PByte; cdecl;
  TSfmlImageFlipHorizontally = procedure (Image: PSfmlImage); cdecl;
  TSfmlImageFlipVertically = procedure (Image: PSfmlImage); cdecl;

  TSfmlFloatRectContains = function (var Rect: TSfmlFloatRect; X, Y: Single): sfBool; cdecl;
  TSfmlIntRectContains = function (var Rect: TSfmlIntRect; X, Y: LongInt): sfBool; cdecl;
  TSfmlFloatRectIntersects = function (var rect1, rect2: TSfmlFloatRect; var Intersection: TSfmlFloatRect): sfBool; cdecl;
  TSfmlIntRectIntersects = function (var rect1, rect2: TSfmlIntRect; var Intersection: TSfmlFloatRect): sfBool; cdecl;

  TSfmlRectangleShapeCreate = function : PSfmlRectangleShape; cdecl;
  TSfmlRectangleShapeCopy = function (const Shape: PSfmlRectangleShape): PSfmlRectangleShape; cdecl;
  TSfmlRectangleShapeDestroy = procedure (Shape: PSfmlRectangleShape); cdecl;
  TSfmlRectangleShapeSetPosition = procedure (Shape: PSfmlRectangleShape; Position: TSfmlVector2f); cdecl;
  TSfmlRectangleShapeSetRotation = procedure (Shape: PSfmlRectangleShape; Angle: Single); cdecl;
  TSfmlRectangleShapeSetScale = procedure (Shape: PSfmlRectangleShape; Scale: TSfmlVector2f); cdecl;
  TSfmlRectangleShapeSetOrigin = procedure (Shape: PSfmlRectangleShape; Origin: TSfmlVector2f); cdecl;
  TSfmlRectangleShapeGetPosition = function (const Shape: PSfmlRectangleShape): TSfmlVector2f; cdecl;
  TSfmlRectangleShapeGetRotation = function (const Shape: PSfmlRectangleShape): Single; cdecl;
  TSfmlRectangleShapeGetScale = function (const Shape: PSfmlRectangleShape): TSfmlVector2f; cdecl;
  TSfmlRectangleShapeGetOrigin = function (const Shape: PSfmlRectangleShape): TSfmlVector2f; cdecl;
  TSfmlRectangleShapeMove = procedure (Shape: PSfmlRectangleShape; Offset: TSfmlVector2f); cdecl;
  TSfmlRectangleShapeRotate = procedure (Shape: PSfmlRectangleShape; Angle: Single); cdecl;
  TSfmlRectangleShapeScale = procedure (Shape: PSfmlRectangleShape; Factors: TSfmlVector2f); cdecl;
  TSfmlRectangleShapeGetTransform = function (const Shape: PSfmlRectangleShape): TSfmlTransform; cdecl;
  TSfmlRectangleShapeGetInverseTransform = function (const Shape: PSfmlRectangleShape): TSfmlTransform; cdecl;
  TSfmlRectangleShapeSetTexture = procedure (Shape: PSfmlRectangleShape; const Texture: PSfmlTexture; resetRect: sfBool); cdecl;
  TSfmlRectangleShapeSetTextureRect = procedure (Shape: PSfmlRectangleShape; rect: TSfmlIntRect); cdecl;
  TSfmlRectangleShapeSetFillColor = procedure (Shape: PSfmlRectangleShape; Color: TSfmlColor); cdecl;
  TSfmlRectangleShapeSetOutlineColor = procedure (Shape: PSfmlRectangleShape; Color: TSfmlColor); cdecl;
  TSfmlRectangleShapeSetOutlineThickness = procedure (Shape: PSfmlRectangleShape; Thickness: Single); cdecl;
  TSfmlRectangleShapeGetTexture = function (const Shape: PSfmlRectangleShape): PSfmlTexture; cdecl;
  TSfmlRectangleShapeGetTextureRect = function (const Shape: PSfmlRectangleShape): TSfmlIntRect; cdecl;
  TSfmlRectangleShapeGetFillColor = function (const Shape: PSfmlRectangleShape): TSfmlColor; cdecl;
  TSfmlRectangleShapeGetOutlineColor = function (const Shape: PSfmlRectangleShape): TSfmlColor; cdecl;
  TSfmlRectangleShapeGetOutlineThickness = function (const Shape: PSfmlRectangleShape): Single; cdecl;
  TSfmlRectangleShapeGetPointCount = function (const Shape: PSfmlRectangleShape): Cardinal; cdecl;
  TSfmlRectangleShapeGetPoint = function (const Shape: PSfmlRectangleShape; Index: Cardinal): TSfmlVector2f; cdecl;
  TSfmlRectangleShapeSetSize = procedure (Shape: PSfmlRectangleShape; Size: TSfmlVector2f); cdecl;
  TSfmlRectangleShapeGetSize = function (const Shape: PSfmlRectangleShape): TSfmlVector2f; cdecl;
  TSfmlRectangleShapeGetLocalBounds = function (const Shape: PSfmlRectangleShape): TSfmlFloatRect; cdecl;
  TSfmlRectangleShapeGetGlobalBounds = function (const Shape: PSfmlRectangleShape): TSfmlFloatRect; cdecl;

  TSfmlRenderTextureCreate = function (Width, Height: Cardinal; depthBuffer: sfBool): PSfmlRenderTexture; cdecl;
  TSfmlRenderTextureDestroy = procedure (RenderTexture: PSfmlRenderTexture); cdecl;
  TSfmlRenderTextureGetSize = function (const RenderTexture: PSfmlRenderTexture): TSfmlVector2u; cdecl;
  TSfmlRenderTextureSetActive = function (RenderTexture: PSfmlRenderTexture; Active: sfBool): sfBool; cdecl;
  TSfmlRenderTextureDisplay = procedure (RenderTexture: PSfmlRenderTexture); cdecl;
  TSfmlRenderTextureClear = procedure (RenderTexture: PSfmlRenderTexture; Color: TSfmlColor); cdecl;
  TSfmlRenderTextureSetView = procedure (RenderTexture: PSfmlRenderTexture; const View: PSfmlView); cdecl;
  TSfmlRenderTextureGetView = function (const RenderTexture: PSfmlRenderTexture): PSfmlView; cdecl;
  TSfmlRenderTextureGetDefaultView = function (const RenderTexture: PSfmlRenderTexture): PSfmlView; cdecl;
  TSfmlRenderTextureGetViewport = function (const RenderTexture: PSfmlRenderTexture; const View: PSfmlView): TSfmlIntRect; cdecl;
  TSfmlRenderTextureMapPixelToCoords = function (const RenderTexture: PSfmlRenderTexture; point: TSfmlVector2i; const View: PSfmlView): TSfmlVector2f; cdecl;
  TSfmlRenderTextureMapCoordsToPixel = function (const RenderTexture: PSfmlRenderTexture; point: TSfmlVector2i; const View: PSfmlView): TSfmlVector2i; cdecl;
  TSfmlRenderTextureDrawSprite = procedure (RenderTexture: PSfmlRenderTexture; const &Object: PSfmlSprite; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderTextureDrawText = procedure (RenderTexture: PSfmlRenderTexture; const &Object: PSfmlText; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderTextureDrawShape = procedure (RenderTexture: PSfmlRenderTexture; const &Object: PSfmlShape; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderTextureDrawCircleShape = procedure (RenderTexture: PSfmlRenderTexture; const &Object: PSfmlCircleShape; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderTextureDrawConvexShape = procedure (RenderTexture: PSfmlRenderTexture; const &Object: PSfmlConvexShape; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderTextureDrawRectangleShape = procedure (RenderTexture: PSfmlRenderTexture; const &Object: PSfmlRectangleShape; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderTextureDrawVertexArray = procedure (RenderTexture: PSfmlRenderTexture; const &Object: PSfmlVertexArray; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderTextureDrawPrimitives = procedure (RenderTexture: PSfmlRenderTexture); cdecl;
  TSfmlRenderTexturePushGLStates = procedure (RenderTexture: PSfmlRenderTexture); cdecl;
  TSfmlRenderTexturePopGLStates = procedure (RenderTexture: PSfmlRenderTexture); cdecl;
  TSfmlRenderTextureResetGLStates = procedure (RenderTexture: PSfmlRenderTexture); cdecl;
  TSfmlRenderTextureGetTexture = function (const RenderTexture: PSfmlRenderTexture): PSfmlTexture ; cdecl;
  TSfmlRenderTextureSetSmooth = procedure (RenderTexture: PSfmlRenderTexture; Smooth: sfBool); cdecl;
  TSfmlRenderTextureIsSmooth = function (const RenderTexture: PSfmlRenderTexture): sfBool; cdecl;
  TSfmlRenderTextureSetRepeated = procedure (RenderTexture: PSfmlRenderTexture; Repeated: sfBool); cdecl;
  TSfmlRenderTextureIsRepeated = function (const RenderTexture: PSfmlRenderTexture): sfBool; cdecl;

  TSfmlRenderWindowCreate = function (Mode: TSfmlVideoMode; const Title: PAnsiChar; Style: TSfmlWindowStyles; const Settings: PSfmlContextSettings): PSfmlRenderWindow; cdecl;
  TSfmlRenderWindowCreateUnicode = function (Mode: TSfmlVideoMode; const Title: PWideChar; Style: TSfmlWindowStyles; const Settings: PSfmlContextSettings): PSfmlRenderWindow; cdecl;
  TSfmlRenderWindowCreateFromHandle = function (Handle: TSfmlWindowHandle; const Settings: PSfmlContextSettings): PSfmlRenderWindow; cdecl;
  TSfmlRenderWindowDestroy = procedure (RenderWindow: PSfmlRenderWindow); cdecl;
  TSfmlRenderWindowClose = procedure (RenderWindow: PSfmlRenderWindow); cdecl;
  TSfmlRenderWindowIsOpen = function (const RenderWindow: PSfmlRenderWindow): sfBool; cdecl;
  TSfmlRenderWindowGetSettings = function (const RenderWindow: PSfmlRenderWindow): TSfmlContextSettings; cdecl;
  TSfmlRenderWindowPollEvent = function (RenderWindow: PSfmlRenderWindow; Event: PSfmlEvent): sfBool; cdecl;
  TSfmlRenderWindowWaitEvent = function (RenderWindow: PSfmlRenderWindow; Event: PSfmlEvent): sfBool; cdecl;
  TSfmlRenderWindowGetPosition = function (const RenderWindow: PSfmlRenderWindow): TSfmlVector2i; cdecl;
  TSfmlRenderWindowSetPosition = procedure (RenderWindow: PSfmlRenderWindow; Position: TSfmlVector2i); cdecl;
  TSfmlRenderWindowGetSize = function (const RenderWindow: PSfmlRenderWindow): TSfmlVector2u; cdecl;
  TSfmlRenderWindowSetSize = procedure (RenderWindow: PSfmlRenderWindow; Size: TSfmlVector2u); cdecl;
  TSfmlRenderWindowSetTitle = procedure (RenderWindow: PSfmlRenderWindow; const Title: PAnsiChar); cdecl;
  TSfmlRenderWindowSetUnicodeTitle = procedure (RenderWindow: PSfmlRenderWindow; const Title: PWideChar); cdecl;
  TSfmlRenderWindowSetIcon = procedure (RenderWindow: PSfmlRenderWindow; Width, Height: Cardinal; const Pixels: PByte); cdecl;
  TSfmlRenderWindowSetVisible = procedure (RenderWindow: PSfmlRenderWindow; Visible: sfBool); cdecl;
  TSfmlRenderWindowSetMouseCursorVisible = procedure (RenderWindow: PSfmlRenderWindow; show: sfBool); cdecl;
  TSfmlRenderWindowSetVerticalSyncEnabled = procedure (RenderWindow: PSfmlRenderWindow; enabled: sfBool); cdecl;
  TSfmlRenderWindowSetKeyRepeatEnabled = procedure (RenderWindow: PSfmlRenderWindow; enabled: sfBool); cdecl;
  TSfmlRenderWindowSetActive = function (RenderWindow: PSfmlRenderWindow; Active: sfBool): sfBool; cdecl;
  TSfmlRenderWindowRequestFocus = procedure (RenderWindow: PSfmlRenderWindow); cdecl;
  TSfmlRenderWindowHasFocus = function (const RenderWindow: PSfmlRenderWindow): sfBool; cdecl;
  TSfmlRenderWindowDisplay = procedure (RenderWindow: PSfmlRenderWindow); cdecl;
  TSfmlRenderWindowSetFramerateLimit = procedure (RenderWindow: PSfmlRenderWindow; Limit: Cardinal); cdecl;
  TSfmlRenderWindowSetJoystickThreshold = procedure (RenderWindow: PSfmlRenderWindow; Threshold: Single); cdecl;
  TSfmlRenderWindowGetSystemHandle = function (const RenderWindow: PSfmlRenderWindow): TSfmlWindowHandle; cdecl;
  TSfmlRenderWindowClear = procedure (RenderWindow: PSfmlRenderWindow; Color: TSfmlColor); cdecl;
  TSfmlRenderWindowSetView = procedure (RenderWindow: PSfmlRenderWindow; const View: PSfmlView); cdecl;
  TSfmlRenderWindowGetView = function (const RenderWindow: PSfmlRenderWindow): PSfmlView; cdecl;
  TSfmlRenderWindowGetDefaultView = function (const RenderWindow: PSfmlRenderWindow): PSfmlView; cdecl;
  TSfmlRenderWindowGetViewport = function (const RenderWindow: PSfmlRenderWindow; const View: PSfmlView): TSfmlIntRect; cdecl;
  TSfmlRenderWindowMapPixelToCoords = function (const RenderWindow: PSfmlRenderWindow; Point: TSfmlVector2i; const View: PSfmlView): TSfmlVector2f; cdecl;
  TSfmlRenderWindowMapCoordsToPixel = function (const RenderWindow: PSfmlRenderWindow; Point: TSfmlVector2i; const View: PSfmlView): TSfmlVector2i; cdecl;
  TSfmlRenderWindowDrawSprite = procedure (RenderWindow: PSfmlRenderWindow; const &Object: PSfmlSprite; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderWindowDrawText = procedure (RenderWindow: PSfmlRenderWindow; const &Object: PSfmlText; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderWindowDrawShape = procedure (RenderWindow: PSfmlRenderWindow; const &Object: PSfmlShape; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderWindowDrawCircleShape = procedure (RenderWindow: PSfmlRenderWindow; const &Object: PSfmlCircleShape; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderWindowDrawConvexShape = procedure (RenderWindow: PSfmlRenderWindow; const &Object: PSfmlConvexShape; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderWindowDrawRectangleShape = procedure (RenderWindow: PSfmlRenderWindow; const &Object: PSfmlRectangleShape; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderWindowDrawVertexArray = procedure (RenderWindow: PSfmlRenderWindow; const &Object: PSfmlVertexArray; const States: PSfmlRenderStates); cdecl;
  TSfmlRenderWindowDrawPrimitives = procedure (RenderWindow: PSfmlRenderWindow); cdecl;
  TSfmlRenderWindowPushGLStates = procedure (RenderWindow: PSfmlRenderWindow); cdecl;
  TSfmlRenderWindowPopGLStates = procedure (RenderWindow: PSfmlRenderWindow); cdecl;
  TSfmlRenderWindowResetGLStates = procedure (RenderWindow: PSfmlRenderWindow); cdecl;
  TSfmlRenderWindowCapture = function (const RenderWindow: PSfmlRenderWindow): PSfmlImage; cdecl;
  TSfmlMouseGetPositionRenderWindow = function (const relativeTo: PSfmlRenderWindow): TSfmlVector2i; cdecl;
  TSfmlMouseSetPositionRenderWindow = procedure (position: TSfmlVector2i; const RelativeTo: PSfmlRenderWindow); cdecl;
  TSfmlTouchGetPositionRenderWindow = function (Finger: Cardinal; const RelativeTo: PSfmlRenderWindow): TSfmlVector2i; cdecl;

  TSfmlShaderCreateFromFile = function (const VertexShaderFilename: PAnsiChar; const FragmentShaderFilename: PAnsiChar): PSfmlShader; cdecl;
  TSfmlShaderCreateFromMemory = function (const VertexShader: PAnsiChar; const FragmentShader: PAnsiChar): PSfmlShader; cdecl;
  TSfmlShaderCreateFromStream = function (VertexShaderStream: PSfmlInputStream; FragmentShaderStream: PSfmlInputStream): PSfmlShader; cdecl;
  TSfmlShaderDestroy = procedure (Shader: PSfmlShader); cdecl;
  TSfmlShaderSetFloatParameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; X: Single); cdecl;
  TSfmlShaderSetFloat2Parameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; X, Y: Single); cdecl;
  TSfmlShaderSetFloat3Parameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; X, Y, Z: Single); cdecl;
  TSfmlShaderSetFloat4Parameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; X, Y, Z, W: Single); cdecl;
  TSfmlShaderSetVector2Parameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; Vector: TSfmlVector2f); cdecl;
  TSfmlShaderSetVector3Parameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; Vector: TSfmlVector3f); cdecl;
  TSfmlShaderSetColorParameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; Color: TSfmlColor); cdecl;
  TSfmlShaderSetTransformParameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; Transform: TSfmlTransform); cdecl;
  TSfmlShaderSetTextureParameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar; const Texture: PSfmlTexture); cdecl;
  TSfmlShaderSetCurrentTextureParameter = procedure (Shader: PSfmlShader; const Name: PAnsiChar); cdecl;
  TSfmlShaderBind = procedure (const Shader: PSfmlShader); cdecl;
  TSfmlShaderIsAvailable = function : sfBool; cdecl;

  TSfmlShapeCreate = function (getPointCount: TSfmlShapeGetPointCountCallback; GetPoint: TSfmlShapeGetPointCallback; userData: Pointer): PSfmlShape; cdecl;
  TSfmlShapeDestroy = procedure (Shape: PSfmlShape); cdecl;
  TSfmlShapeSetPosition = procedure (Shape: PSfmlShape; Position: TSfmlVector2f); cdecl;
  TSfmlShapeSetRotation = procedure (Shape: PSfmlShape; Angle: Single); cdecl;
  TSfmlShapeSetScale = procedure (Shape: PSfmlShape; Scale: TSfmlVector2f); cdecl;
  TSfmlShapeSetOrigin = procedure (Shape: PSfmlShape; Origin: TSfmlVector2f); cdecl;
  TSfmlShapeGetPosition = function (const Shape: PSfmlShape): TSfmlVector2f; cdecl;
  TSfmlShapeGetRotation = function (const Shape: PSfmlShape): Single; cdecl;
  TSfmlShapeGetScale = function (const Shape: PSfmlShape): TSfmlVector2f; cdecl;
  TSfmlShapeGetOrigin = function (const Shape: PSfmlShape): TSfmlVector2f; cdecl;
  TSfmlShapeMove = procedure (Shape: PSfmlShape; Offset: TSfmlVector2f); cdecl;
  TSfmlShapeRotate = procedure (Shape: PSfmlShape; Angle: Single); cdecl;
  TSfmlShapeScale = procedure (Shape: PSfmlShape; Factors: TSfmlVector2f); cdecl;
  TSfmlShapeGetTransform = function (const Shape: PSfmlShape): TSfmlTransform; cdecl;
  TSfmlShapeGetInverseTransform = function (const Shape: PSfmlShape): TSfmlTransform; cdecl;
  TSfmlShapeSetTexture = procedure (Shape: PSfmlShape; const Texture: PSfmlTexture; ResetRect: sfBool); cdecl;
  TSfmlShapeSetTextureRect = procedure (Shape: PSfmlShape; Rect: TSfmlIntRect); cdecl;
  TSfmlShapeSetFillColor = procedure (Shape: PSfmlShape; Color: TSfmlColor); cdecl;
  TSfmlShapeSetOutlineColor = procedure (Shape: PSfmlShape; Color: TSfmlColor); cdecl;
  TSfmlShapeSetOutlineThickness = procedure (Shape: PSfmlShape; Thickness: Single); cdecl;
  TSfmlShapeGetTexture = function (const Shape: PSfmlShape): PSfmlTexture; cdecl;
  TSfmlShapeGetTextureRect = function (const Shape: PSfmlShape): TSfmlIntRect; cdecl;
  TSfmlShapeGetFillColor = function (const Shape: PSfmlShape): TSfmlColor; cdecl;
  TSfmlShapeGetOutlineColor = function (const Shape: PSfmlShape): TSfmlColor; cdecl;
  TSfmlShapeGetOutlineThickness = function (const Shape: PSfmlShape): Single; cdecl;
  TSfmlShapeGetPointCount = function (const Shape: PSfmlShape): Cardinal; cdecl;
  TSfmlShapeGetPoint = function (const Shape: PSfmlShape; Index: Cardinal): TSfmlVector2f; cdecl;
  TSfmlShapeGetLocalBounds = function (const Shape: PSfmlShape): TSfmlFloatRect; cdecl;
  TSfmlShapeGetGlobalBounds = function (const Shape: PSfmlShape): TSfmlFloatRect; cdecl;
  TSfmlShapeUpdate = procedure (Shape: PSfmlShape); cdecl;

  TSfmlSpriteCreate = function : PSfmlSprite; cdecl;
  TSfmlSpriteCopy = function (const Sprite: PSfmlSprite): PSfmlSprite; cdecl;
  TSfmlSpriteDestroy = procedure (Sprite: PSfmlSprite); cdecl;
  TSfmlSpriteSetPosition = procedure (Sprite: PSfmlSprite; Position: TSfmlVector2f); cdecl;
  TSfmlSpriteSetRotation = procedure (Sprite: PSfmlSprite; Angle: Single); cdecl;
  TSfmlSpriteSetScale = procedure (Sprite: PSfmlSprite; Scale: TSfmlVector2f); cdecl;
  TSfmlSpriteSetOrigin = procedure (Sprite: PSfmlSprite; Origin: TSfmlVector2f); cdecl;
  TSfmlSpriteGetPosition = function (const Sprite: PSfmlSprite): TSfmlVector2f; cdecl;
  TSfmlSpriteGetRotation = function (const Sprite: PSfmlSprite): Single; cdecl;
  TSfmlSpriteGetScale = function (const Sprite: PSfmlSprite): TSfmlVector2f; cdecl;
  TSfmlSpriteGetOrigin = function (const Sprite: PSfmlSprite): TSfmlVector2f; cdecl;
  TSfmlSpriteMove = procedure (Sprite: PSfmlSprite; Offset: TSfmlVector2f); cdecl;
  TSfmlSpriteRotate = procedure (Sprite: PSfmlSprite; Angle: Single); cdecl;
  TSfmlSpriteScale = procedure (Sprite: PSfmlSprite; Factors: TSfmlVector2f); cdecl;
  TSfmlSpriteGetTransform = function (const Sprite: PSfmlSprite): TSfmlTransform; cdecl;
  TSfmlSpriteGetInverseTransform = function (const Sprite: PSfmlSprite): TSfmlTransform; cdecl;
  TSfmlSpriteSetTexture = procedure (Sprite: PSfmlSprite; const Texture: PSfmlTexture; resetRect: sfBool); cdecl;
  TSfmlSpriteSetTextureRect = procedure (Sprite: PSfmlSprite; Rectangle: TSfmlIntRect); cdecl;
  TSfmlSpriteSetColor = procedure (Sprite: PSfmlSprite; Color: TSfmlColor); cdecl;
  TSfmlSpriteGetTexture = function (const Sprite: PSfmlSprite): PSfmlTexture; cdecl;
  TSfmlSpriteGetTextureRect = function (const Sprite: PSfmlSprite): TSfmlIntRect; cdecl;
  TSfmlSpriteGetColor = function (const Sprite: PSfmlSprite): TSfmlColor; cdecl;
  TSfmlSpriteGetLocalBounds = function (const Sprite: PSfmlSprite): TSfmlFloatRect; cdecl;
  TSfmlSpriteGetGlobalBounds = function (const Sprite: PSfmlSprite): TSfmlFloatRect; cdecl;

  TSfmlTextCreate = function : PSfmlText; cdecl;
  TSfmlTextCopy = function (const Text: PSfmlText): PSfmlText; cdecl;
  TSfmlTextDestroy = procedure (Text: PSfmlText); cdecl;
  TSfmlTextSetPosition = procedure (Text: PSfmlText; Position: TSfmlVector2f); cdecl;
  TSfmlTextSetRotation = procedure (Text: PSfmlText; Angle: Single); cdecl;
  TSfmlTextSetScale = procedure (Text: PSfmlText; Scale: TSfmlVector2f); cdecl;
  TSfmlTextSetOrigin = procedure (Text: PSfmlText; Origin: TSfmlVector2f); cdecl;
  TSfmlTextGetPosition = function (const Text: PSfmlText): TSfmlVector2f; cdecl;
  TSfmlTextGetRotation = function (const Text: PSfmlText): Single; cdecl;
  TSfmlTextGetScale = function (const Text: PSfmlText): TSfmlVector2f; cdecl;
  TSfmlTextGetOrigin = function (const Text: PSfmlText): TSfmlVector2f; cdecl;
  TSfmlTextMove = procedure (Text: PSfmlText; Offset: TSfmlVector2f); cdecl;
  TSfmlTextRotate = procedure (Text: PSfmlText; Angle: Single); cdecl;
  TSfmlTextScale = procedure (Text: PSfmlText; Factors: TSfmlVector2f); cdecl;
  TSfmlTextGetTransform = function (const Text: PSfmlText): TSfmlTransform; cdecl;
  TSfmlTextGetInverseTransform = function (const Text: PSfmlText): TSfmlTransform; cdecl;
  TSfmlTextSetString = procedure (Text: PSfmlText; const &string: PAnsiChar); cdecl;
  TSfmlTextSetUnicodeString = procedure (Text: PSfmlText; const &string: PWideChar); cdecl;
  TSfmlTextSetFont = procedure (Text: PSfmlText; const Font: PSfmlFont); cdecl;
  TSfmlTextSetCharacterSize = procedure (Text: PSfmlText; Size: Cardinal); cdecl;
  TSfmlTextSetStyle = procedure (Text: PSfmlText; Style: sfUint32); cdecl;
  TSfmlTextSetColor = procedure (Text: PSfmlText; Color: TSfmlColor); cdecl;
  TSfmlTextGetString = function (const Text: PSfmlText): PAnsiChar; cdecl;
  TSfmlTextGetUnicodeString = function (const Text: PSfmlText): PWideChar; cdecl;
  TSfmlTextGetFont = function (const Text: PSfmlText): PSfmlFont; cdecl;
  TSfmlTextGetCharacterSize = function (const Text: PSfmlText): Cardinal; cdecl;
  TSfmlTextGetStyle = function (const Text: PSfmlText): sfUint32; cdecl;
  TSfmlTextGetColor = function (const Text: PSfmlText): TSfmlColor; cdecl;
  TSfmlTextFindCharacterPos = function (const Text: PSfmlText; Index: NativeUInt): TSfmlVector2f; cdecl;
  TSfmlTextGetLocalBounds = function (const Text: PSfmlText): TSfmlFloatRect; cdecl;
  TSfmlTextGetGlobalBounds = function (const Text: PSfmlText): TSfmlFloatRect; cdecl;

  TSfmlTextureCreate = function (Width, Height: Cardinal): PSfmlTexture; cdecl;
  TSfmlTextureCreateFromFile = function (const FileName: PAnsiChar; const Area: PSfmlIntRect): PSfmlTexture; cdecl;
  TSfmlTextureCreateFromMemory = function (const data: Pointer; SizeInBytes: NativeUInt; const Area: PSfmlIntRect): PSfmlTexture; cdecl;
  TSfmlTextureCreateFromStream = function (Stream: PSfmlInputStream; const Area: PSfmlIntRect): PSfmlTexture; cdecl;
  TSfmlTextureCreateFromImage = function (const Image: PSfmlImage; const Area: PSfmlIntRect): PSfmlTexture; cdecl;
  TSfmlTextureCopy = function (const Texture: PSfmlTexture): PSfmlTexture; cdecl;
  TSfmlTextureDestroy = procedure (Texture: PSfmlTexture); cdecl;
  TSfmlTextureGetSize = function (const Texture: PSfmlTexture): TSfmlVector2u; cdecl;
  TSfmlTextureCopyToImage = function (const Texture: PSfmlTexture): PSfmlImage; cdecl;
  TSfmlTextureUpdateFromPixels = procedure (Texture: PSfmlTexture; const Pixels: PByte; Width, Height, X, Y: Cardinal); cdecl;
  TSfmlTextureUpdateFromImage = procedure (Texture: PSfmlTexture; const Image: PSfmlImage; X, Y: Cardinal); cdecl;
  TSfmlTextureUpdateFromWindow = procedure (Texture: PSfmlTexture; const Window: PSfmlWindow; X, Y: Cardinal); cdecl;
  TSfmlTextureUpdateFromRenderWindow = procedure (Texture: PSfmlTexture; const RenderWindow: PSfmlRenderWindow; X, Y: Cardinal); cdecl;
  TSfmlTextureSetSmooth = procedure (Texture: PSfmlTexture; Smooth: sfBool); cdecl;
  TSfmlTextureIsSmooth = function (const Texture: PSfmlTexture): sfBool; cdecl;
  TSfmlTextureSetRepeated = procedure (Texture: PSfmlTexture; Repeated: sfBool); cdecl;
  TSfmlTextureIsRepeated = function (const Texture: PSfmlTexture): sfBool; cdecl;
  TSfmlTextureBind = procedure (const Texture: PSfmlTexture); cdecl;
  TsfmlTextureGetMaximumSize = function : Cardinal; cdecl;

  TSfmlTransformIdentity = function : TSfmlTransform; cdecl;
  TSfmlTransformFromMatrix = function (a00, a01, a02, a10, a11, a12, a20, a21, a22: Single): TSfmlTransform; cdecl;
  TSfmlTransformGetMatrix = procedure (const Transform: PSfmlTransform; Matrix: PSingle); cdecl;
  TSfmlTransformGetInverse = function (const Transform: PSfmlTransform): TSfmlTransform; cdecl;
  TSfmlTransformTransformPoint = function (const Transform: PSfmlTransform; Point: TSfmlVector2f): TSfmlVector2f; cdecl;
  TSfmlTransformTransformRect = function (const Transform: PSfmlTransform; Rectangle: TSfmlFloatRect): TSfmlFloatRect; cdecl;
  TSfmlTransformCombine = procedure (Transform: PSfmlTransform; const Other: PSfmlTransform); cdecl;
  TSfmlTransformTranslate = procedure (Transform: PSfmlTransform; X, Y: Single); cdecl;
  TSfmlTransformRotate = procedure (Transform: PSfmlTransform; Angle: Single); cdecl;
  TSfmlTransformRotateWithCenter = procedure (Transform: PSfmlTransform; Angle: Single; centerX, centerY: Single); cdecl;
  TSfmlTransformScale = procedure (Transform: PSfmlTransform; ScaleX, ScaleY: Single); cdecl;
  TSfmlTransformScaleWithCenter = procedure (Transform: PSfmlTransform; ScaleX, ScaleY, CenterX, CenterY: Single); cdecl;

  TSfmlTransformableCreate = function : PSfmlTransformable; cdecl;
  TSfmlTransformableCopy = function (const Transformable: PSfmlTransformable): PSfmlTransformable; cdecl;
  TSfmlTransformableDestroy = procedure (Transformable: PSfmlTransformable); cdecl;
  TSfmlTransformableSetPosition = procedure (Transformable: PSfmlTransformable; Position: TSfmlVector2f); cdecl;
  TSfmlTransformableSetRotation = procedure (Transformable: PSfmlTransformable; Angle: Single); cdecl;
  TSfmlTransformableSetScale = procedure (Transformable: PSfmlTransformable; Scale: TSfmlVector2f); cdecl;
  TSfmlTransformableSetOrigin = procedure (Transformable: PSfmlTransformable; Origin: TSfmlVector2f); cdecl;
  TSfmlTransformableGetPosition = function (const Transformable: PSfmlTransformable): TSfmlVector2f; cdecl;
  TSfmlTransformableGetRotation = function (const Transformable: PSfmlTransformable): Single; cdecl;
  TSfmlTransformableGetScale = function (const Transformable: PSfmlTransformable): TSfmlVector2f; cdecl;
  TSfmlTransformableGetOrigin = function (const Transformable: PSfmlTransformable): TSfmlVector2f; cdecl;
  TSfmlTransformableMove = procedure (Transformable: PSfmlTransformable; Offset: TSfmlVector2f); cdecl;
  TSfmlTransformableRotate = procedure (Transformable: PSfmlTransformable; Angle: Single); cdecl;
  TSfmlTransformableScale = procedure (Transformable: PSfmlTransformable; Factors: TSfmlVector2f); cdecl;
  TSfmlTransformableGetTransform = function (const Transformable: PSfmlTransformable): TSfmlTransform; cdecl;
  TSfmlTransformableGetInverseTransform = function (const Transformable: PSfmlTransformable): TSfmlTransform; cdecl;

  TSfmlVertexArrayCreate = function : PSfmlVertexArray; cdecl;
  TSfmlVertexArrayCopy = function (const VertexArray: PSfmlVertexArray): PSfmlVertexArray; cdecl;
  TSfmlVertexArrayDestroy = procedure (VertexArray: PSfmlVertexArray); cdecl;
  TSfmlVertexArrayGetVertexCount = function (const VertexArray: PSfmlVertexArray): Cardinal; cdecl;
  TSfmlVertexArrayGetVertex = function (VertexArray: PSfmlVertexArray; Index: Cardinal): PSfmlVertex; cdecl;
  TSfmlVertexArrayClear = procedure (VertexArray: PSfmlVertexArray); cdecl;
  TSfmlVertexArrayResize = procedure (VertexArray: PSfmlVertexArray; VertexCount: Cardinal); cdecl;
  TSfmlVertexArrayAppend = procedure (VertexArray: PSfmlVertexArray; Vertex: TSfmlVertex); cdecl;
  TSfmlVertexArraySetPrimitiveType = procedure (VertexArray: PSfmlVertexArray; &Type: TSfmlPrimitiveType); cdecl;
  TSfmlVertexArrayGetPrimitiveType = function (VertexArray: PSfmlVertexArray): TSfmlPrimitiveType; cdecl;
  TSfmlVertexArrayGetBounds = function (VertexArray: PSfmlVertexArray): TSfmlFloatRect; cdecl;

  TSfmlViewCreate = function : PSfmlView; cdecl;
  TSfmlViewCreateFromRect = function (Rectangle: TSfmlFloatRect): PSfmlView; cdecl;
  TSfmlViewCopy = function (const View: PSfmlView): PSfmlView; cdecl;
  TSfmlViewDestroy = procedure (View: PSfmlView); cdecl;
  TSfmlViewSetCenter = procedure (View: PSfmlView; Center: TSfmlVector2f); cdecl;
  TSfmlViewSetSize = procedure (View: PSfmlView; Size: TSfmlVector2f); cdecl;
  TSfmlViewSetRotation = procedure (View: PSfmlView; Angle: Single); cdecl;
  TSfmlViewSetViewport = procedure (View: PSfmlView; Viewport: TSfmlFloatRect); cdecl;
  TSfmlViewReset = procedure (View: PSfmlView; Rectangle: TSfmlFloatRect); cdecl;
  TSfmlViewGetCenter = function (const View: PSfmlView): TSfmlVector2f; cdecl;
  TSfmlViewGetSize = function (const View: PSfmlView): TSfmlVector2f; cdecl;
  TSfmlViewGetRotation = function (const View: PSfmlView): Single; cdecl;
  TSfmlViewGetViewport = function (const View: PSfmlView): TSfmlFloatRect; cdecl;
  TSfmlViewMove = procedure (View: PSfmlView; Offset: TSfmlVector2f); cdecl;
  TSfmlViewRotate = procedure (View: PSfmlView; Angle: Single); cdecl;
  TSfmlViewZoom = procedure (View: PSfmlView; Factor: Single); cdecl;

var
  SfmlBlendAlpha: TSfmlBlendAlpha;
  SfmlBlendAdd: TSfmlBlendAdd;
  SfmlBlendMultiply: TSfmlBlendMultiply;
  SfmlBlendNone: TSfmlBlendNone;

  SfmlBlack: TSfmlColor;
  SfmlWhite: TSfmlColor;
  SfmlRed: TSfmlColor;
  SfmlGreen: TSfmlColor;
  SfmlBlue: TSfmlColor;
  SfmlYellow: TSfmlColor;
  SfmlMagenta: TSfmlColor;
  SfmlCyan: TSfmlColor;
  SfmlTransparent: TSfmlColor;

(*
  SfmlBlack: TSfmlBlack;
  SfmlWhite: TSfmlWhite;
  SfmlRed: TSfmlRed;
  SfmlGreen: TSfmlGreen;
  SfmlBlue: TSfmlBlue;
  SfmlYellow: TSfmlYellow;
  SfmlMagenta: TSfmlMagenta;
  SfmlCyan: TSfmlCyan;
  SfmlTransparent: TSfmlTransparent;
*)
  SfmlColorFromRGB: TSfmlColorFromRGB;
  SfmlColorFromRGBA: TSfmlColorFromRGBA;
  SfmlColorAdd: TSfmlColorAdd;
  SfmlColorModulate: TSfmlColorModulate;

  SfmlCircleShapeCreate: TSfmlCircleShapeCreate;
  SfmlCircleShapeCopy: TSfmlCircleShapeCopy;
  SfmlCircleShapeDestroy: TSfmlCircleShapeDestroy;
  SfmlCircleShapeSetPosition: TSfmlCircleShapeSetPosition;
  SfmlCircleShapeSetRotation: TSfmlCircleShapeSetRotation;
  SfmlCircleShapeSetScale: TSfmlCircleShapeSetScale;
  SfmlCircleShapeSetOrigin: TSfmlCircleShapeSetOrigin;
  SfmlCircleShapeGetPosition: TSfmlCircleShapeGetPosition;
  SfmlCircleShapeGetRotation: TSfmlCircleShapeGetRotation;
  SfmlCircleShapeGetScale: TSfmlCircleShapeGetScale;
  SfmlCircleShapeGetOrigin: TSfmlCircleShapeGetOrigin;
  SfmlCircleShapeMove: TSfmlCircleShapeMove;
  SfmlCircleShapeRotate: TSfmlCircleShapeRotate;
  SfmlCircleShapeScale: TSfmlCircleShapeScale;
  SfmlCircleShapeGetTransform: TSfmlCircleShapeGetTransform;
  SfmlCircleShapeGetInverseTransform: TSfmlCircleShapeGetInverseTransform;
  SfmlCircleShapeSetTexture: TSfmlCircleShapeSetTexture;
  SfmlCircleShapeSetTextureRect: TSfmlCircleShapeSetTextureRect;
  SfmlCircleShapeSetFillColor: TSfmlCircleShapeSetFillColor;
  SfmlCircleShapeSetOutlineColor: TSfmlCircleShapeSetOutlineColor;
  SfmlCircleShapeSetOutlineThickness: TSfmlCircleShapeSetOutlineThickness;
  SfmlCircleShapeGetTexture: TSfmlCircleShapeGetTexture;
  SfmlCircleShapeGetTextureRect: TSfmlCircleShapeGetTextureRect;
  SfmlCircleShapeGetFillColor: TSfmlCircleShapeGetFillColor;
  SfmlCircleShapeGetOutlineColor: TSfmlCircleShapeGetOutlineColor;
  SfmlCircleShapeGetOutlineThickness: TSfmlCircleShapeGetOutlineThickness;
  SfmlCircleShapeGetPointCount: TSfmlCircleShapeGetPointCount;
  SfmlCircleShapeGetPoint: TSfmlCircleShapeGetPoint;
  SfmlCircleShapeSetRadius: TSfmlCircleShapeSetRadius;
  SfmlCircleShapeGetRadius: TSfmlCircleShapeGetRadius;
  SfmlCircleShapeSetPointCount: TSfmlCircleShapeSetPointCount;
  SfmlCircleShapeGetLocalBounds: TSfmlCircleShapeGetLocalBounds;
  SfmlCircleShapeGetGlobalBounds: TSfmlCircleShapeGetGlobalBounds;

  SfmlConvexShapeCreate: TSfmlConvexShapeCreate;
  SfmlConvexShapeCopy: TSfmlConvexShapeCopy;
  SfmlConvexShapeDestroy: TSfmlConvexShapeDestroy;
  SfmlConvexShapeSetPosition: TSfmlConvexShapeSetPosition;
  SfmlConvexShapeSetRotation: TSfmlConvexShapeSetRotation;
  SfmlConvexShapeSetScale: TSfmlConvexShapeSetScale;
  SfmlConvexShapeSetOrigin: TSfmlConvexShapeSetOrigin;
  SfmlConvexShapeGetPosition: TSfmlConvexShapeGetPosition;
  SfmlConvexShapeGetRotation: TSfmlConvexShapeGetRotation;
  SfmlConvexShapeGetScale: TSfmlConvexShapeGetScale;
  SfmlConvexShapeGetOrigin: TSfmlConvexShapeGetOrigin;
  SfmlConvexShapeMove: TSfmlConvexShapeMove;
  SfmlConvexShapeRotate: TSfmlConvexShapeRotate;
  SfmlConvexShapeScale: TSfmlConvexShapeScale;
  SfmlConvexShapeGetTransform: TSfmlConvexShapeGetTransform;
  SfmlConvexShapeGetInverseTransform: TSfmlConvexShapeGetInverseTransform;
  SfmlConvexShapeSetTexture: TSfmlConvexShapeSetTexture;
  SfmlConvexShapeSetTextureRect: TSfmlConvexShapeSetTextureRect;
  SfmlConvexShapeSetFillColor: TSfmlConvexShapeSetFillColor;
  SfmlConvexShapeSetOutlineColor: TSfmlConvexShapeSetOutlineColor;
  SfmlConvexShapeSetOutlineThickness: TSfmlConvexShapeSetOutlineThickness;
  SfmlConvexShapeGetTexture: TSfmlConvexShapeGetTexture;
  SfmlConvexShapeGetTextureRect: TSfmlConvexShapeGetTextureRect;
  SfmlConvexShapeGetFillColor: TSfmlConvexShapeGetFillColor;
  SfmlConvexShapeGetOutlineColor: TSfmlConvexShapeGetOutlineColor;
  SfmlConvexShapeGetOutlineThickness: TSfmlConvexShapeGetOutlineThickness;
  SfmlConvexShapeGetPointCount: TSfmlConvexShapeGetPointCount;
  SfmlConvexShapeGetPoint: TSfmlConvexShapeGetPoint;
  SfmlConvexShapeSetPointCount: TSfmlConvexShapeSetPointCount;
  SfmlConvexShapeSetPoint: TSfmlConvexShapeSetPoint;
  SfmlConvexShapeGetLocalBounds: TSfmlConvexShapeGetLocalBounds;
  SfmlConvexShapeGetGlobalBounds: TSfmlConvexShapeGetGlobalBounds;

  SfmlFontCreateFromFile: TSfmlFontCreateFromFile;
  SfmlFontCreateFromMemory: TSfmlFontCreateFromMemory;
  SfmlFontCreateFromStream: TSfmlFontCreateFromStream;
  SfmlFontCopy: TSfmlFontCopy;
  SfmlFontDestroy: TSfmlFontDestroy;
  SfmlFontGetGlyph: TSfmlFontGetGlyph;
  SfmlFontGetKerning: TSfmlFontGetKerning;
  SfmlFontGetLineSpacing: TSfmlFontGetLineSpacing;
  SfmlFontGetUnderlinePosition: TSfmlFontGetUnderlinePosition;
  SfmlFontGetUnderlineThickness: TSfmlFontGetUnderlineThickness;
  SfmlFontGetTexture: TSfmlFontGetTexture;
  SfmlFontGetInfo: TSfmlFontGetInfo;

  SfmlImageCreate: TSfmlImageCreate;
  SfmlImageCreateFromColor: TSfmlImageCreateFromColor;
  SfmlImageCreateFromPixels: TSfmlImageCreateFromPixels;
  SfmlImageCreateFromFile: TSfmlImageCreateFromFile;
  SfmlImageCreateFromMemory: TSfmlImageCreateFromMemory;
  SfmlImageCreateFromStream: TSfmlImageCreateFromStream;
  SfmlImageCopy: TSfmlImageCopy;
  SfmlImageDestroy: TSfmlImageDestroy;
  SfmlImageSaveToFile: TSfmlImageSaveToFile;
  SfmlImageGetSize: TSfmlImageGetSize;
  SfmlImageCreateMaskFromColor: TSfmlImageCreateMaskFromColor;
  SfmlImageCopyImage: TSfmlImageCopyImage;
  SfmlImageSetPixel: TSfmlImageSetPixel;
  SfmlImageGetPixel: TSfmlImageGetPixel;
  SfmlImageGetPixelsPtr: TSfmlImageGetPixelsPtr;
  SfmlImageFlipHorizontally: TSfmlImageFlipHorizontally;
  SfmlImageFlipVertically: TSfmlImageFlipVertically;

  SfmlFloatRectContains: TSfmlFloatRectContains;
  SfmlIntRectContains: TSfmlIntRectContains;
  SfmlFloatRectIntersects: TSfmlFloatRectIntersects;
  SfmlIntRectIntersects: TSfmlIntRectIntersects;

  SfmlRectangleShapeCreate: TSfmlRectangleShapeCreate;
  SfmlRectangleShapeCopy: TSfmlRectangleShapeCopy;
  SfmlRectangleShapeDestroy: TSfmlRectangleShapeDestroy;
  SfmlRectangleShapeSetPosition: TSfmlRectangleShapeSetPosition;
  SfmlRectangleShapeSetRotation: TSfmlRectangleShapeSetRotation;
  SfmlRectangleShapeSetScale: TSfmlRectangleShapeSetScale;
  SfmlRectangleShapeSetOrigin: TSfmlRectangleShapeSetOrigin;
  SfmlRectangleShapeGetPosition: TSfmlRectangleShapeGetPosition;
  SfmlRectangleShapeGetRotation: TSfmlRectangleShapeGetRotation;
  SfmlRectangleShapeGetScale: TSfmlRectangleShapeGetScale;
  SfmlRectangleShapeGetOrigin: TSfmlRectangleShapeGetOrigin;
  SfmlRectangleShapeMove: TSfmlRectangleShapeMove;
  SfmlRectangleShapeRotate: TSfmlRectangleShapeRotate;
  SfmlRectangleShapeScale: TSfmlRectangleShapeScale;
  SfmlRectangleShapeGetTransform: TSfmlRectangleShapeGetTransform;
  SfmlRectangleShapeGetInverseTransform: TSfmlRectangleShapeGetInverseTransform;
  SfmlRectangleShapeSetTexture: TSfmlRectangleShapeSetTexture;
  SfmlRectangleShapeSetTextureRect: TSfmlRectangleShapeSetTextureRect;
  SfmlRectangleShapeSetFillColor: TSfmlRectangleShapeSetFillColor;
  SfmlRectangleShapeSetOutlineColor: TSfmlRectangleShapeSetOutlineColor;
  SfmlRectangleShapeSetOutlineThickness: TSfmlRectangleShapeSetOutlineThickness;
  SfmlRectangleShapeGetTexture: TSfmlRectangleShapeGetTexture;
  SfmlRectangleShapeGetTextureRect: TSfmlRectangleShapeGetTextureRect;
  SfmlRectangleShapeGetFillColor: TSfmlRectangleShapeGetFillColor;
  SfmlRectangleShapeGetOutlineColor: TSfmlRectangleShapeGetOutlineColor;
  SfmlRectangleShapeGetOutlineThickness: TSfmlRectangleShapeGetOutlineThickness;
  SfmlRectangleShapeGetPointCount: TSfmlRectangleShapeGetPointCount;
  SfmlRectangleShapeGetPoint: TSfmlRectangleShapeGetPoint;
  SfmlRectangleShapeSetSize: TSfmlRectangleShapeSetSize;
  SfmlRectangleShapeGetSize: TSfmlRectangleShapeGetSize;
  SfmlRectangleShapeGetLocalBounds: TSfmlRectangleShapeGetLocalBounds;
  SfmlRectangleShapeGetGlobalBounds: TSfmlRectangleShapeGetGlobalBounds;

  SfmlRenderTextureCreate: TSfmlRenderTextureCreate;
  SfmlRenderTextureDestroy: TSfmlRenderTextureDestroy;
  SfmlRenderTextureGetSize: TSfmlRenderTextureGetSize;
  SfmlRenderTextureSetActive: TSfmlRenderTextureSetActive;
  SfmlRenderTextureDisplay: TSfmlRenderTextureDisplay;
  SfmlRenderTextureClear: TSfmlRenderTextureClear;
  SfmlRenderTextureSetView: TSfmlRenderTextureSetView;
  SfmlRenderTextureGetView: TSfmlRenderTextureGetView;
  SfmlRenderTextureGetDefaultView: TSfmlRenderTextureGetDefaultView;
  SfmlRenderTextureGetViewport: TSfmlRenderTextureGetViewport;
  SfmlRenderTextureMapPixelToCoords: TSfmlRenderTextureMapPixelToCoords;
  SfmlRenderTextureMapCoordsToPixel: TSfmlRenderTextureMapCoordsToPixel;
  SfmlRenderTextureDrawSprite: TSfmlRenderTextureDrawSprite;
  SfmlRenderTextureDrawText: TSfmlRenderTextureDrawText;
  SfmlRenderTextureDrawShape: TSfmlRenderTextureDrawShape;
  SfmlRenderTextureDrawCircleShape: TSfmlRenderTextureDrawCircleShape;
  SfmlRenderTextureDrawConvexShape: TSfmlRenderTextureDrawConvexShape;
  SfmlRenderTextureDrawRectangleShape: TSfmlRenderTextureDrawRectangleShape;
  SfmlRenderTextureDrawVertexArray: TSfmlRenderTextureDrawVertexArray;
  SfmlRenderTextureDrawPrimitives: TSfmlRenderTextureDrawPrimitives;
  SfmlRenderTexturePushGLStates: TSfmlRenderTexturePushGLStates;
  SfmlRenderTexturePopGLStates: TSfmlRenderTexturePopGLStates;
  SfmlRenderTextureResetGLStates: TSfmlRenderTextureResetGLStates;
  SfmlRenderTextureGetTexture: TSfmlRenderTextureGetTexture;
  SfmlRenderTextureSetSmooth: TSfmlRenderTextureSetSmooth;
  SfmlRenderTextureIsSmooth: TSfmlRenderTextureIsSmooth;
  SfmlRenderTextureSetRepeated: TSfmlRenderTextureSetRepeated;
  SfmlRenderTextureIsRepeated: TSfmlRenderTextureIsRepeated;

  SfmlRenderWindowCreate: TSfmlRenderWindowCreate;
  SfmlRenderWindowCreateUnicode: TSfmlRenderWindowCreateUnicode;
  SfmlRenderWindowCreateFromHandle: TSfmlRenderWindowCreateFromHandle;
  SfmlRenderWindowDestroy: TSfmlRenderWindowDestroy;
  SfmlRenderWindowClose: TSfmlRenderWindowClose;
  SfmlRenderWindowIsOpen: TSfmlRenderWindowIsOpen;
  SfmlRenderWindowGetSettings: TSfmlRenderWindowGetSettings;
  SfmlRenderWindowPollEvent: TSfmlRenderWindowPollEvent;
  SfmlRenderWindowWaitEvent: TSfmlRenderWindowWaitEvent;
  SfmlRenderWindowGetPosition: TSfmlRenderWindowGetPosition;
  SfmlRenderWindowSetPosition: TSfmlRenderWindowSetPosition;
  SfmlRenderWindowGetSize: TSfmlRenderWindowGetSize;
  SfmlRenderWindowSetSize: TSfmlRenderWindowSetSize;
  SfmlRenderWindowSetTitle: TSfmlRenderWindowSetTitle;
  SfmlRenderWindowSetUnicodeTitle: TSfmlRenderWindowSetUnicodeTitle;
  SfmlRenderWindowSetIcon: TSfmlRenderWindowSetIcon;
  SfmlRenderWindowSetVisible: TSfmlRenderWindowSetVisible;
  SfmlRenderWindowSetMouseCursorVisible: TSfmlRenderWindowSetMouseCursorVisible;
  SfmlRenderWindowSetVerticalSyncEnabled: TSfmlRenderWindowSetVerticalSyncEnabled;
  SfmlRenderWindowSetKeyRepeatEnabled: TSfmlRenderWindowSetKeyRepeatEnabled;
  SfmlRenderWindowSetActive: TSfmlRenderWindowSetActive;
  SfmlRenderWindowRequestFocus: TSfmlRenderWindowRequestFocus;
  SfmlRenderWindowHasFocus: TSfmlRenderWindowHasFocus;
  SfmlRenderWindowDisplay: TSfmlRenderWindowDisplay;
  SfmlRenderWindowSetFramerateLimit: TSfmlRenderWindowSetFramerateLimit;
  SfmlRenderWindowSetJoystickThreshold: TSfmlRenderWindowSetJoystickThreshold;
  SfmlRenderWindowGetSystemHandle: TSfmlRenderWindowGetSystemHandle;
  SfmlRenderWindowClear: TSfmlRenderWindowClear;
  SfmlRenderWindowSetView: TSfmlRenderWindowSetView;
  SfmlRenderWindowGetView: TSfmlRenderWindowGetView;
  SfmlRenderWindowGetDefaultView: TSfmlRenderWindowGetDefaultView;
  SfmlRenderWindowGetViewport: TSfmlRenderWindowGetViewport;
  SfmlRenderWindowMapPixelToCoords: TSfmlRenderWindowMapPixelToCoords;
  SfmlRenderWindowMapCoordsToPixel: TSfmlRenderWindowMapCoordsToPixel;
  SfmlRenderWindowDrawSprite: TSfmlRenderWindowDrawSprite;
  SfmlRenderWindowDrawText: TSfmlRenderWindowDrawText;
  SfmlRenderWindowDrawShape: TSfmlRenderWindowDrawShape;
  SfmlRenderWindowDrawCircleShape: TSfmlRenderWindowDrawCircleShape;
  SfmlRenderWindowDrawConvexShape: TSfmlRenderWindowDrawConvexShape;
  SfmlRenderWindowDrawRectangleShape: TSfmlRenderWindowDrawRectangleShape;
  SfmlRenderWindowDrawVertexArray: TSfmlRenderWindowDrawVertexArray;
  SfmlRenderWindowDrawPrimitives: TSfmlRenderWindowDrawPrimitives;
  SfmlRenderWindowPushGLStates: TSfmlRenderWindowPushGLStates;
  SfmlRenderWindowPopGLStates: TSfmlRenderWindowPopGLStates;
  SfmlRenderWindowResetGLStates: TSfmlRenderWindowResetGLStates;
  SfmlRenderWindowCapture: TSfmlRenderWindowCapture;
  SfmlMouseGetPositionRenderWindow: TSfmlMouseGetPositionRenderWindow;
  SfmlMouseSetPositionRenderWindow: TSfmlMouseSetPositionRenderWindow;
  SfmlTouchGetPositionRenderWindow: TSfmlTouchGetPositionRenderWindow;

  SfmlShaderCreateFromFile: TSfmlShaderCreateFromFile;
  SfmlShaderCreateFromMemory: TSfmlShaderCreateFromMemory;
  SfmlShaderCreateFromStream: TSfmlShaderCreateFromStream;
  SfmlShaderDestroy: TSfmlShaderDestroy;
  SfmlShaderSetFloatParameter: TSfmlShaderSetFloatParameter;
  SfmlShaderSetFloat2Parameter: TSfmlShaderSetFloat2Parameter;
  SfmlShaderSetFloat3Parameter: TSfmlShaderSetFloat3Parameter;
  SfmlShaderSetFloat4Parameter: TSfmlShaderSetFloat4Parameter;
  SfmlShaderSetVector2Parameter: TSfmlShaderSetVector2Parameter;
  SfmlShaderSetVector3Parameter: TSfmlShaderSetVector3Parameter;
  SfmlShaderSetColorParameter: TSfmlShaderSetColorParameter;
  SfmlShaderSetTransformParameter: TSfmlShaderSetTransformParameter;
  SfmlShaderSetTextureParameter: TSfmlShaderSetTextureParameter;
  SfmlShaderSetCurrentTextureParameter: TSfmlShaderSetCurrentTextureParameter;
  SfmlShaderBind: TSfmlShaderBind;
  SfmlShaderIsAvailable: TSfmlShaderIsAvailable;

  SfmlShapeCreate: TSfmlShapeCreate;
  SfmlShapeDestroy: TSfmlShapeDestroy;
  SfmlShapeSetPosition: TSfmlShapeSetPosition;
  SfmlShapeSetRotation: TSfmlShapeSetRotation;
  SfmlShapeSetScale: TSfmlShapeSetScale;
  SfmlShapeSetOrigin: TSfmlShapeSetOrigin;
  SfmlShapeGetPosition: TSfmlShapeGetPosition;
  SfmlShapeGetRotation: TSfmlShapeGetRotation;
  SfmlShapeGetScale: TSfmlShapeGetScale;
  SfmlShapeGetOrigin: TSfmlShapeGetOrigin;
  SfmlShapeMove: TSfmlShapeMove;
  SfmlShapeRotate: TSfmlShapeRotate;
  SfmlShapeScale: TSfmlShapeScale;
  SfmlShapeGetTransform: TSfmlShapeGetTransform;
  SfmlShapeGetInverseTransform: TSfmlShapeGetInverseTransform;
  SfmlShapeSetTexture: TSfmlShapeSetTexture;
  SfmlShapeSetTextureRect: TSfmlShapeSetTextureRect;
  SfmlShapeSetFillColor: TSfmlShapeSetFillColor;
  SfmlShapeSetOutlineColor: TSfmlShapeSetOutlineColor;
  SfmlShapeSetOutlineThickness: TSfmlShapeSetOutlineThickness;
  SfmlShapeGetTexture: TSfmlShapeGetTexture;
  SfmlShapeGetTextureRect: TSfmlShapeGetTextureRect;
  SfmlShapeGetFillColor: TSfmlShapeGetFillColor;
  SfmlShapeGetOutlineColor: TSfmlShapeGetOutlineColor;
  SfmlShapeGetOutlineThickness: TSfmlShapeGetOutlineThickness;
  SfmlShapeGetPointCount: TSfmlShapeGetPointCount;
  SfmlShapeGetPoint: TSfmlShapeGetPoint;
  SfmlShapeGetLocalBounds: TSfmlShapeGetLocalBounds;
  SfmlShapeGetGlobalBounds: TSfmlShapeGetGlobalBounds;
  SfmlShapeUpdate: TSfmlShapeUpdate;

  SfmlSpriteCreate: TSfmlSpriteCreate;
  SfmlSpriteCopy: TSfmlSpriteCopy;
  SfmlSpriteDestroy: TSfmlSpriteDestroy;
  SfmlSpriteSetPosition: TSfmlSpriteSetPosition;
  SfmlSpriteSetRotation: TSfmlSpriteSetRotation;
  SfmlSpriteSetScale: TSfmlSpriteSetScale;
  SfmlSpriteSetOrigin: TSfmlSpriteSetOrigin;
  SfmlSpriteGetPosition: TSfmlSpriteGetPosition;
  SfmlSpriteGetRotation: TSfmlSpriteGetRotation;
  SfmlSpriteGetScale: TSfmlSpriteGetScale;
  SfmlSpriteGetOrigin: TSfmlSpriteGetOrigin;
  SfmlSpriteMove: TSfmlSpriteMove;
  SfmlSpriteRotate: TSfmlSpriteRotate;
  SfmlSpriteScale: TSfmlSpriteScale;
  SfmlSpriteGetTransform: TSfmlSpriteGetTransform;
  SfmlSpriteGetInverseTransform: TSfmlSpriteGetInverseTransform;
  SfmlSpriteSetTexture: TSfmlSpriteSetTexture;
  SfmlSpriteSetTextureRect: TSfmlSpriteSetTextureRect;
  SfmlSpriteSetColor: TSfmlSpriteSetColor;
  SfmlSpriteGetTexture: TSfmlSpriteGetTexture;
  SfmlSpriteGetTextureRect: TSfmlSpriteGetTextureRect;
  SfmlSpriteGetColor: TSfmlSpriteGetColor;
  SfmlSpriteGetLocalBounds: TSfmlSpriteGetLocalBounds;
  SfmlSpriteGetGlobalBounds: TSfmlSpriteGetGlobalBounds;

  SfmlTextCreate: TSfmlTextCreate;
  SfmlTextCopy: TSfmlTextCopy;
  SfmlTextDestroy: TSfmlTextDestroy;
  SfmlTextSetPosition: TSfmlTextSetPosition;
  SfmlTextSetRotation: TSfmlTextSetRotation;
  SfmlTextSetScale: TSfmlTextSetScale;
  SfmlTextSetOrigin: TSfmlTextSetOrigin;
  SfmlTextGetPosition: TSfmlTextGetPosition;
  SfmlTextGetRotation: TSfmlTextGetRotation;
  SfmlTextGetScale: TSfmlTextGetScale;
  SfmlTextGetOrigin: TSfmlTextGetOrigin;
  SfmlTextMove: TSfmlTextMove;
  SfmlTextRotate: TSfmlTextRotate;
  SfmlTextScale: TSfmlTextScale;
  SfmlTextGetTransform: TSfmlTextGetTransform;
  SfmlTextGetInverseTransform: TSfmlTextGetInverseTransform;
  SfmlTextSetString: TSfmlTextSetString;
  SfmlTextSetUnicodeString: TSfmlTextSetUnicodeString;
  SfmlTextSetFont: TSfmlTextSetFont;
  SfmlTextSetCharacterSize: TSfmlTextSetCharacterSize;
  SfmlTextSetStyle: TSfmlTextSetStyle;
  SfmlTextSetColor: TSfmlTextSetColor;
  SfmlTextGetString: TSfmlTextGetString;
  SfmlTextGetUnicodeString: TSfmlTextGetUnicodeString;
  SfmlTextGetFont: TSfmlTextGetFont;
  SfmlTextGetCharacterSize: TSfmlTextGetCharacterSize;
  SfmlTextGetStyle: TSfmlTextGetStyle;
  SfmlTextGetColor: TSfmlTextGetColor;
  SfmlTextFindCharacterPos: TSfmlTextFindCharacterPos;
  SfmlTextGetLocalBounds: TSfmlTextGetLocalBounds;
  SfmlTextGetGlobalBounds: TSfmlTextGetGlobalBounds;

  SfmlTextureCreate: TSfmlTextureCreate;
  SfmlTextureCreateFromFile: TSfmlTextureCreateFromFile;
  SfmlTextureCreateFromMemory: TSfmlTextureCreateFromMemory;
  SfmlTextureCreateFromStream: TSfmlTextureCreateFromStream;
  SfmlTextureCreateFromImage: TSfmlTextureCreateFromImage;
  SfmlTextureCopy: TSfmlTextureCopy;
  SfmlTextureDestroy: TSfmlTextureDestroy;
  SfmlTextureGetSize: TSfmlTextureGetSize;
  SfmlTextureCopyToImage: TSfmlTextureCopyToImage;
  SfmlTextureUpdateFromPixels: TSfmlTextureUpdateFromPixels;
  SfmlTextureUpdateFromImage: TSfmlTextureUpdateFromImage;
  SfmlTextureUpdateFromWindow: TSfmlTextureUpdateFromWindow;
  SfmlTextureUpdateFromRenderWindow: TSfmlTextureUpdateFromRenderWindow;
  SfmlTextureSetSmooth: TSfmlTextureSetSmooth;
  SfmlTextureIsSmooth: TSfmlTextureIsSmooth;
  SfmlTextureSetRepeated: TSfmlTextureSetRepeated;
  SfmlTextureIsRepeated: TSfmlTextureIsRepeated;
  SfmlTextureBind: TSfmlTextureBind;
  SfmlTextureGetMaximumSize: TsfmlTextureGetMaximumSize;

  SfmlTransformIdentity: TSfmlTransformIdentity;
  SfmlTransformFromMatrix: TSfmlTransformFromMatrix;
  SfmlTransformGetMatrix: TSfmlTransformGetMatrix;
  SfmlTransformGetInverse: TSfmlTransformGetInverse;
  SfmlTransformTransformPoint: TSfmlTransformTransformPoint;
  SfmlTransformTransformRect: TSfmlTransformTransformRect;
  SfmlTransformCombine: TSfmlTransformCombine;
  SfmlTransformTranslate: TSfmlTransformTranslate;
  SfmlTransformRotate: TSfmlTransformRotate;
  SfmlTransformRotateWithCenter: TSfmlTransformRotateWithCenter;
  SfmlTransformScale: TSfmlTransformScale;
  SfmlTransformScaleWithCenter: TSfmlTransformScaleWithCenter;

  SfmlTransformableCreate: TSfmlTransformableCreate;
  SfmlTransformableCopy: TSfmlTransformableCopy;
  SfmlTransformableDestroy: TSfmlTransformableDestroy;
  SfmlTransformableSetPosition: TSfmlTransformableSetPosition;
  SfmlTransformableSetRotation: TSfmlTransformableSetRotation;
  SfmlTransformableSetScale: TSfmlTransformableSetScale;
  SfmlTransformableSetOrigin: TSfmlTransformableSetOrigin;
  SfmlTransformableGetPosition: TSfmlTransformableGetPosition;
  SfmlTransformableGetRotation: TSfmlTransformableGetRotation;
  SfmlTransformableGetScale: TSfmlTransformableGetScale;
  SfmlTransformableGetOrigin: TSfmlTransformableGetOrigin;
  SfmlTransformableMove: TSfmlTransformableMove;
  SfmlTransformableRotate: TSfmlTransformableRotate;
  SfmlTransformableScale: TSfmlTransformableScale;
  SfmlTransformableGetTransform: TSfmlTransformableGetTransform;
  SfmlTransformableGetInverseTransform: TSfmlTransformableGetInverseTransform;

  SfmlVertexArrayCreate: TSfmlVertexArrayCreate;
  SfmlVertexArrayCopy: TSfmlVertexArrayCopy;
  SfmlVertexArrayDestroy: TSfmlVertexArrayDestroy;
  SfmlVertexArrayGetVertexCount: TSfmlVertexArrayGetVertexCount;
  SfmlVertexArrayGetVertex: TSfmlVertexArrayGetVertex;
  SfmlVertexArrayClear: TSfmlVertexArrayClear;
  SfmlVertexArrayResize: TSfmlVertexArrayResize;
  SfmlVertexArrayAppend: TSfmlVertexArrayAppend;
  SfmlVertexArraySetPrimitiveType: TSfmlVertexArraySetPrimitiveType;
  SfmlVertexArrayGetPrimitiveType: TSfmlVertexArrayGetPrimitiveType;
  SfmlVertexArrayGetBounds: TSfmlVertexArrayGetBounds;

  SfmlViewCreate: TSfmlViewCreate;
  SfmlViewCreateFromRect: TSfmlViewCreateFromRect;
  SfmlViewCopy: TSfmlViewCopy;
  SfmlViewDestroy: TSfmlViewDestroy;
  SfmlViewSetCenter: TSfmlViewSetCenter;
  SfmlViewSetSize: TSfmlViewSetSize;
  SfmlViewSetRotation: TSfmlViewSetRotation;
  SfmlViewSetViewport: TSfmlViewSetViewport;
  SfmlViewReset: TSfmlViewReset;
  SfmlViewGetCenter: TSfmlViewGetCenter;
  SfmlViewGetSize: TSfmlViewGetSize;
  SfmlViewGetRotation: TSfmlViewGetRotation;
  SfmlViewGetViewport: TSfmlViewGetViewport;
  SfmlViewMove: TSfmlViewMove;
  SfmlViewRotate: TSfmlViewRotate;
  SfmlViewZoom: TSfmlViewZoom;

implementation

var
  CSfmlGraphicsHandle: HINST;
{$IF Defined(MSWINDOWS)}
  CSfmlGraphicsLibrary: PAnsiChar = 'csfml-graphics-2.dll';
{$ELSEIF Defined(DARWIN)}
  error, not yet defined
{$ELSEIF Defined(UNIX)}
  error, not yet defined
{$IFEND}

procedure InitDLL;

  function BindFunction(Name: AnsiString): Pointer;
  begin
    Result := GetProcAddress(CSfmlGraphicsHandle, PAnsiChar(Name));
    Assert(Assigned(Result));
  end;

begin
  CSfmlGraphicsHandle := LoadLibraryA(CSfmlGraphicsLibrary);
  if CSfmlGraphicsHandle <> 0 then
    try
      SfmlBlendAlpha := BindFunction('sfBlendAlpha');
      SfmlBlendAdd := BindFunction('sfBlendAdd');
      SfmlBlendMultiply := BindFunction('sfBlendMultiply');
      SfmlBlendNone := BindFunction('sfBlendNone');

      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfBlack'))^, SfmlBlack, 4);
      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfWhite'))^, SfmlWhite, 4);
      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfRed'))^, SfmlRed, 4);
      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfGreen'))^, SfmlGreen, 4);
      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfBlue'))^, SfmlBlue, 4);
      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfYellow'))^, SfmlYellow, 4);
      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfMagenta'))^, SfmlMagenta, 4);
      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfCyan'))^, SfmlCyan, 4);
      Move(GetProcAddress(CSfmlGraphicsHandle, PAnsiChar('sfTransparent'))^, SfmlTransparent, 4);

      SfmlColorFromRGB := BindFunction('sfColor_fromRGB');
      SfmlColorFromRGBA := BindFunction('sfColor_fromRGBA');
      SfmlColorAdd := BindFunction('sfColor_add');
      SfmlColorModulate := BindFunction('sfColor_modulate');
      SfmlCircleShapeCreate := BindFunction('sfCircleShape_create');
      SfmlCircleShapeCopy := BindFunction('sfCircleShape_copy');
      SfmlCircleShapeDestroy := BindFunction('sfCircleShape_destroy');
      SfmlCircleShapeSetPosition := BindFunction('sfCircleShape_setPosition');
      SfmlCircleShapeSetRotation := BindFunction('sfCircleShape_setRotation');
      SfmlCircleShapeSetScale := BindFunction('sfCircleShape_setScale');
      SfmlCircleShapeSetOrigin := BindFunction('sfCircleShape_setOrigin');
      SfmlCircleShapeGetPosition := BindFunction('sfCircleShape_getPosition');
      SfmlCircleShapeGetRotation := BindFunction('sfCircleShape_getRotation');
      SfmlCircleShapeGetScale := BindFunction('sfCircleShape_getScale');
      SfmlCircleShapeGetOrigin := BindFunction('sfCircleShape_getOrigin');
      SfmlCircleShapeMove := BindFunction('sfCircleShape_move');
      SfmlCircleShapeRotate := BindFunction('sfCircleShape_rotate');
      SfmlCircleShapeScale := BindFunction('sfCircleShape_scale');
      SfmlCircleShapeGetTransform := BindFunction('sfCircleShape_getTransform');
      SfmlCircleShapeGetInverseTransform := BindFunction('sfCircleShape_getInverseTransform');
      SfmlCircleShapeSetTexture := BindFunction('sfCircleShape_setTexture');
      SfmlCircleShapeSetTextureRect := BindFunction('sfCircleShape_setTextureRect');
      SfmlCircleShapeSetFillColor := BindFunction('sfCircleShape_setFillColor');
      SfmlCircleShapeSetOutlineColor := BindFunction('sfCircleShape_setOutlineColor');
      SfmlCircleShapeSetOutlineThickness := BindFunction('sfCircleShape_setOutlineThickness');
      SfmlCircleShapeGetTexture := BindFunction('sfCircleShape_getTexture');
      SfmlCircleShapeGetTextureRect := BindFunction('sfCircleShape_getTextureRect');
      SfmlCircleShapeGetFillColor := BindFunction('sfCircleShape_getFillColor');
      SfmlCircleShapeGetOutlineColor := BindFunction('sfCircleShape_getOutlineColor');
      SfmlCircleShapeGetOutlineThickness := BindFunction('sfCircleShape_getOutlineThickness');
      SfmlCircleShapeGetPointCount := BindFunction('sfCircleShape_getPointCount');
      SfmlCircleShapeGetPoint := BindFunction('sfCircleShape_getPoint');
      SfmlCircleShapeSetRadius := BindFunction('sfCircleShape_setRadius');
      SfmlCircleShapeGetRadius := BindFunction('sfCircleShape_getRadius');
      SfmlCircleShapeSetPointCount := BindFunction('sfCircleShape_setPointCount');
      SfmlCircleShapeGetLocalBounds := BindFunction('sfCircleShape_getLocalBounds');
      SfmlCircleShapeGetGlobalBounds := BindFunction('sfCircleShape_getGlobalBounds');
      SfmlConvexShapeCreate:= BindFunction('sfConvexShape_create');
      SfmlConvexShapeCopy := BindFunction('sfConvexShape_copy');
      SfmlConvexShapeDestroy := BindFunction('sfConvexShape_destroy');
      SfmlConvexShapeSetPosition := BindFunction('sfConvexShape_setPosition');
      SfmlConvexShapeSetRotation := BindFunction('sfConvexShape_setRotation');
      SfmlConvexShapeSetScale := BindFunction('sfConvexShape_setScale');
      SfmlConvexShapeSetOrigin := BindFunction('sfConvexShape_setOrigin');
      SfmlConvexShapeGetPosition := BindFunction('sfConvexShape_getPosition');
      SfmlConvexShapeGetRotation := BindFunction('sfConvexShape_getRotation');
      SfmlConvexShapeGetScale := BindFunction('sfConvexShape_getScale');
      SfmlConvexShapeGetOrigin := BindFunction('sfConvexShape_getOrigin');
      SfmlConvexShapeMove := BindFunction('sfConvexShape_move');
      SfmlConvexShapeRotate := BindFunction('sfConvexShape_rotate');
      SfmlConvexShapeScale := BindFunction('sfConvexShape_scale');
      SfmlConvexShapeGetTransform := BindFunction('sfConvexShape_getTransform');
      SfmlConvexShapeGetInverseTransform := BindFunction('sfConvexShape_getInverseTransform');
      SfmlConvexShapeSetTexture := BindFunction('sfConvexShape_setTexture');
      SfmlConvexShapeSetTextureRect := BindFunction('sfConvexShape_setTextureRect');
      SfmlConvexShapeSetFillColor := BindFunction('sfConvexShape_setFillColor');
      SfmlConvexShapeSetOutlineColor := BindFunction('sfConvexShape_setOutlineColor');
      SfmlConvexShapeSetOutlineThickness := BindFunction('sfConvexShape_setOutlineThickness');
      SfmlConvexShapeGetTexture := BindFunction('sfConvexShape_getTexture');
      SfmlConvexShapeGetTextureRect := BindFunction('sfConvexShape_getTextureRect');
      SfmlConvexShapeGetFillColor := BindFunction('sfConvexShape_getFillColor');
      SfmlConvexShapeGetOutlineColor := BindFunction('sfConvexShape_getOutlineColor');
      SfmlConvexShapeGetOutlineThickness := BindFunction('sfConvexShape_getOutlineThickness');
      SfmlConvexShapeGetPointCount := BindFunction('sfConvexShape_getPointCount');
      SfmlConvexShapeGetPoint := BindFunction('sfConvexShape_getPoint');
      SfmlConvexShapeSetPointCount := BindFunction('sfConvexShape_setPointCount');
      SfmlConvexShapeSetPoint := BindFunction('sfConvexShape_setPoint');
      SfmlConvexShapeGetLocalBounds := BindFunction('sfConvexShape_getLocalBounds');
      SfmlConvexShapeGetGlobalBounds := BindFunction('sfConvexShape_getGlobalBounds');
      SfmlFontCreateFromFile := BindFunction('sfFont_createFromFile');
      SfmlFontCreateFromMemory := BindFunction('sfFont_createFromMemory');
      SfmlFontCreateFromStream := BindFunction('sfFont_createFromStream');
      SfmlFontCopy := BindFunction('sfFont_copy');
      SfmlFontDestroy := BindFunction('sfFont_destroy');
      SfmlFontGetGlyph := BindFunction('sfFont_getGlyph');
      SfmlFontGetKerning := BindFunction('sfFont_getKerning');
      SfmlFontGetLineSpacing := BindFunction('sfFont_getLineSpacing');
      SfmlFontGetUnderlinePosition := BindFunction('sfFont_getUnderlinePosition');
      SfmlFontGetUnderlineThickness := BindFunction('sfFont_getUnderlineThickness');
      SfmlFontGetTexture := BindFunction('sfFont_getTexture');
      SfmlFontGetInfo := BindFunction('sfFont_getInfo');
      SfmlImageCreate := BindFunction('sfImage_create');
      SfmlImageCreateFromColor := BindFunction('sfImage_createFromColor');
      SfmlImageCreateFromPixels := BindFunction('sfImage_createFromPixels');
      SfmlImageCreateFromFile := BindFunction('sfImage_createFromFile');
      SfmlImageCreateFromMemory := BindFunction('sfImage_createFromMemory');
      SfmlImageCreateFromStream := BindFunction('sfImage_createFromStream');
      SfmlImageCopy := BindFunction('sfImage_copy');
      SfmlImageDestroy := BindFunction('sfImage_destroy');
      SfmlImageSaveToFile := BindFunction('sfImage_saveToFile');
      SfmlImageGetSize := BindFunction('sfImage_getSize');
      SfmlImageCreateMaskFromColor := BindFunction('sfImage_createMaskFromColor');
      SfmlImageCopyImage := BindFunction('sfImage_copyImage');
      SfmlImageSetPixel := BindFunction('sfImage_setPixel');
      SfmlImageGetPixel := BindFunction('sfImage_getPixel');
      SfmlImageGetPixelsPtr := BindFunction('sfImage_getPixelsPtr');
      SfmlImageFlipHorizontally := BindFunction('sfImage_flipHorizontally');
      SfmlImageFlipVertically := BindFunction('sfImage_flipVertically');
      SfmlFloatRectContains := BindFunction('sfFloatRect_contains');
      SfmlIntRectContains := BindFunction('sfIntRect_contains');
      SfmlFloatRectIntersects := BindFunction('sfFloatRect_intersects');
      SfmlIntRectIntersects := BindFunction('sfIntRect_intersects');
      SfmlRectangleShapeCreate := BindFunction('sfRectangleShape_create');
      SfmlRectangleShapeCopy := BindFunction('sfRectangleShape_copy');
      SfmlRectangleShapeDestroy := BindFunction('sfRectangleShape_destroy');
      SfmlRectangleShapeSetPosition := BindFunction('sfRectangleShape_setPosition');
      SfmlRectangleShapeSetRotation := BindFunction('sfRectangleShape_setRotation');
      SfmlRectangleShapeSetScale := BindFunction('sfRectangleShape_setScale');
      SfmlRectangleShapeSetOrigin := BindFunction('sfRectangleShape_setOrigin');
      SfmlRectangleShapeGetPosition := BindFunction('sfRectangleShape_getPosition');
      SfmlRectangleShapeGetRotation := BindFunction('sfRectangleShape_getRotation');
      SfmlRectangleShapeGetScale := BindFunction('sfRectangleShape_getScale');
      SfmlRectangleShapeGetOrigin := BindFunction('sfRectangleShape_getOrigin');
      SfmlRectangleShapeMove := BindFunction('sfRectangleShape_move');
      SfmlRectangleShapeRotate := BindFunction('sfRectangleShape_rotate');
      SfmlRectangleShapeScale := BindFunction('sfRectangleShape_scale');
      SfmlRectangleShapeGetTransform := BindFunction('sfRectangleShape_getTransform');
      SfmlRectangleShapeGetInverseTransform := BindFunction('sfRectangleShape_getInverseTransform');
      SfmlRectangleShapeSetTexture := BindFunction('sfRectangleShape_setTexture');
      SfmlRectangleShapeSetTextureRect := BindFunction('sfRectangleShape_setTextureRect');
      SfmlRectangleShapeSetFillColor := BindFunction('sfRectangleShape_setFillColor');
      SfmlRectangleShapeSetOutlineColor := BindFunction('sfRectangleShape_setOutlineColor');
      SfmlRectangleShapeSetOutlineThickness := BindFunction('sfRectangleShape_setOutlineThickness');
      SfmlRectangleShapeGetTexture := BindFunction('sfRectangleShape_getTexture');
      SfmlRectangleShapeGetTextureRect := BindFunction('sfRectangleShape_getTextureRect');
      SfmlRectangleShapeGetFillColor := BindFunction('sfRectangleShape_getFillColor');
      SfmlRectangleShapeGetOutlineColor := BindFunction('sfRectangleShape_getOutlineColor');
      SfmlRectangleShapeGetOutlineThickness := BindFunction('sfRectangleShape_getOutlineThickness');
      SfmlRectangleShapeGetPointCount := BindFunction('sfRectangleShape_getPointCount');
      SfmlRectangleShapeGetPoint := BindFunction('sfRectangleShape_getPoint');
      SfmlRectangleShapeSetSize := BindFunction('sfRectangleShape_setSize');
      SfmlRectangleShapeGetSize := BindFunction('sfRectangleShape_getSize');
      SfmlRectangleShapeGetLocalBounds := BindFunction('sfRectangleShape_getLocalBounds');
      SfmlRectangleShapeGetGlobalBounds := BindFunction('sfRectangleShape_getGlobalBounds');
      SfmlRenderTextureCreate := BindFunction('sfRenderTexture_create');
      SfmlRenderTextureDestroy := BindFunction('sfRenderTexture_destroy');
      SfmlRenderTextureGetSize := BindFunction('sfRenderTexture_getSize');
      SfmlRenderTextureSetActive := BindFunction('sfRenderTexture_setActive');
      SfmlRenderTextureDisplay := BindFunction('sfRenderTexture_display');
      SfmlRenderTextureClear := BindFunction('sfRenderTexture_clear');
      SfmlRenderTextureSetView := BindFunction('sfRenderTexture_setView');
      SfmlRenderTextureGetView := BindFunction('sfRenderTexture_getView');
      SfmlRenderTextureGetDefaultView := BindFunction('sfRenderTexture_getDefaultView');
      SfmlRenderTextureGetViewport := BindFunction('sfRenderTexture_getViewport');
      SfmlRenderTextureMapPixelToCoords := BindFunction('sfRenderTexture_mapPixelToCoords');
      SfmlRenderTextureMapCoordsToPixel := BindFunction('sfRenderTexture_mapCoordsToPixel');
      SfmlRenderTextureDrawSprite := BindFunction('sfRenderTexture_drawSprite');
      SfmlRenderTextureDrawText := BindFunction('sfRenderTexture_drawText');
      SfmlRenderTextureDrawShape := BindFunction('sfRenderTexture_drawShape');
      SfmlRenderTextureDrawCircleShape := BindFunction('sfRenderTexture_drawCircleShape');
      SfmlRenderTextureDrawConvexShape := BindFunction('sfRenderTexture_drawConvexShape');
      SfmlRenderTextureDrawRectangleShape := BindFunction('sfRenderTexture_drawRectangleShape');
      SfmlRenderTextureDrawVertexArray := BindFunction('sfRenderTexture_drawVertexArray');
      SfmlRenderTextureDrawPrimitives := BindFunction('sfRenderTexture_drawPrimitives');
      SfmlRenderTexturePushGLStates := BindFunction('sfRenderTexture_pushGLStates');
      SfmlRenderTexturePopGLStates := BindFunction('sfRenderTexture_popGLStates');
      SfmlRenderTextureResetGLStates := BindFunction('sfRenderTexture_resetGLStates');
      SfmlRenderTextureGetTexture := BindFunction('sfRenderTexture_getTexture');
      SfmlRenderTextureSetSmooth := BindFunction('sfRenderTexture_setSmooth');
      SfmlRenderTextureIsSmooth := BindFunction('sfRenderTexture_isSmooth');
      SfmlRenderTextureSetRepeated := BindFunction('sfRenderTexture_setRepeated');
      SfmlRenderTextureIsRepeated := BindFunction('sfRenderTexture_isRepeated');
      SfmlRenderWindowCreate := BindFunction('sfRenderWindow_create');
      SfmlRenderWindowCreateUnicode := BindFunction('sfRenderWindow_createUnicode');
      SfmlRenderWindowCreateFromHandle := BindFunction('sfRenderWindow_createFromHandle');
      SfmlRenderWindowDestroy := BindFunction('sfRenderWindow_destroy');
      SfmlRenderWindowClose := BindFunction('sfRenderWindow_close');
      SfmlRenderWindowIsOpen := BindFunction('sfRenderWindow_isOpen');
      SfmlRenderWindowGetSettings := BindFunction('sfRenderWindow_getSettings');
      SfmlRenderWindowPollEvent := BindFunction('sfRenderWindow_pollEvent');
      SfmlRenderWindowWaitEvent := BindFunction('sfRenderWindow_waitEvent');
      SfmlRenderWindowGetPosition := BindFunction('sfRenderWindow_getPosition');
      SfmlRenderWindowSetPosition := BindFunction('sfRenderWindow_setPosition');
      SfmlRenderWindowGetSize := BindFunction('sfRenderWindow_getSize');
      SfmlRenderWindowSetSize := BindFunction('sfRenderWindow_setSize');
      SfmlRenderWindowSetTitle := BindFunction('sfRenderWindow_setTitle');
      SfmlRenderWindowSetUnicodeTitle := BindFunction('sfRenderWindow_setUnicodeTitle');
      SfmlRenderWindowSetIcon := BindFunction('sfRenderWindow_setIcon');
      SfmlRenderWindowSetVisible := BindFunction('sfRenderWindow_setVisible');
      SfmlRenderWindowSetMouseCursorVisible := BindFunction('sfRenderWindow_setMouseCursorVisible');
      SfmlRenderWindowSetVerticalSyncEnabled := BindFunction('sfRenderWindow_setVerticalSyncEnabled');
      SfmlRenderWindowSetKeyRepeatEnabled := BindFunction('sfRenderWindow_setKeyRepeatEnabled');
      SfmlRenderWindowSetActive := BindFunction('sfRenderWindow_setActive');
      SfmlRenderWindowRequestFocus := BindFunction('sfRenderWindow_requestFocus');
      SfmlRenderWindowHasFocus := BindFunction('sfRenderWindow_hasFocus');
      SfmlRenderWindowDisplay := BindFunction('sfRenderWindow_display');
      SfmlRenderWindowSetFramerateLimit := BindFunction('sfRenderWindow_setFramerateLimit');
      SfmlRenderWindowSetJoystickThreshold := BindFunction('sfRenderWindow_setJoystickThreshold');
      SfmlRenderWindowGetSystemHandle := BindFunction('sfRenderWindow_getSystemHandle');
      SfmlRenderWindowClear := BindFunction('sfRenderWindow_clear');
      SfmlRenderWindowSetView := BindFunction('sfRenderWindow_setView');
      SfmlRenderWindowGetView := BindFunction('sfRenderWindow_getView');
      SfmlRenderWindowGetDefaultView := BindFunction('sfRenderWindow_getDefaultView');
      SfmlRenderWindowGetViewport := BindFunction('sfRenderWindow_getViewport');
      SfmlRenderWindowMapPixelToCoords := BindFunction('sfRenderWindow_mapPixelToCoords');
      SfmlRenderWindowMapCoordsToPixel := BindFunction('sfRenderWindow_mapCoordsToPixel');
      SfmlRenderWindowDrawSprite := BindFunction('sfRenderWindow_drawSprite');
      SfmlRenderWindowDrawText := BindFunction('sfRenderWindow_drawText');
      SfmlRenderWindowDrawShape := BindFunction('sfRenderWindow_drawShape');
      SfmlRenderWindowDrawCircleShape := BindFunction('sfRenderWindow_drawCircleShape');
      SfmlRenderWindowDrawConvexShape := BindFunction('sfRenderWindow_drawConvexShape');
      SfmlRenderWindowDrawRectangleShape := BindFunction('sfRenderWindow_drawRectangleShape');
      SfmlRenderWindowDrawVertexArray := BindFunction('sfRenderWindow_drawVertexArray');
      SfmlRenderWindowDrawPrimitives := BindFunction('sfRenderWindow_drawPrimitives');
      SfmlRenderWindowPushGLStates := BindFunction('sfRenderWindow_pushGLStates');
      SfmlRenderWindowPopGLStates := BindFunction('sfRenderWindow_popGLStates');
      SfmlRenderWindowResetGLStates := BindFunction('sfRenderWindow_resetGLStates');
      SfmlRenderWindowCapture := BindFunction('sfRenderWindow_capture');
      SfmlMouseGetPositionRenderWindow := BindFunction('sfMouse_getPositionRenderWindow');
      SfmlMouseSetPositionRenderWindow := BindFunction('sfMouse_setPositionRenderWindow');
      SfmlTouchGetPositionRenderWindow := BindFunction('sfTouch_getPositionRenderWindow');
      SfmlShaderCreateFromFile := BindFunction('sfShader_createFromFile');
      SfmlShaderCreateFromMemory := BindFunction('sfShader_createFromMemory');
      SfmlShaderCreateFromStream := BindFunction('sfShader_createFromStream');
      SfmlShaderDestroy := BindFunction('sfShader_destroy');
      SfmlShadersetFloatParameter := BindFunction('sfShader_setFloatParameter');
      SfmlShaderSetFloat2Parameter := BindFunction('sfShader_setFloat2Parameter');
      SfmlShaderSetFloat3Parameter := BindFunction('sfShader_setFloat3Parameter');
      SfmlShaderSetFloat4Parameter := BindFunction('sfShader_setFloat4Parameter');
      SfmlShaderSetVector2Parameter := BindFunction('sfShader_setVector2Parameter');
      SfmlShaderSetVector3Parameter := BindFunction('sfShader_setVector3Parameter');
      SfmlShaderSetColorParameter := BindFunction('sfShader_setColorParameter');
      SfmlShaderSetTransformParameter := BindFunction('sfShader_setTransformParameter');
      SfmlShaderSetTextureParameter := BindFunction('sfShader_setTextureParameter');
      SfmlShaderSetCurrentTextureParameter := BindFunction('sfShader_setCurrentTextureParameter');
      SfmlShaderBind := BindFunction('sfShader_bind');
      SfmlShaderIsAvailable := BindFunction('sfShader_isAvailable');
      SfmlShapeCreate := BindFunction('sfShape_create');
      SfmlShapeDestroy := BindFunction('sfShape_destroy');
      SfmlShapeSetPosition := BindFunction('sfShape_setPosition');
      SfmlShapeSetRotation := BindFunction('sfShape_setRotation');
      SfmlShapeSetScale := BindFunction('sfShape_setScale');
      SfmlShapeSetOrigin := BindFunction('sfShape_setOrigin');
      SfmlShapeGetPosition := BindFunction('sfShape_getPosition');
      SfmlShapeGetRotation := BindFunction('sfShape_getRotation');
      SfmlShapeGetScale := BindFunction('sfShape_getScale');
      SfmlShapeGetOrigin := BindFunction('sfShape_getOrigin');
      SfmlShapeMove := BindFunction('sfShape_move');
      SfmlShapeRotate := BindFunction('sfShape_rotate');
      SfmlShapeScale := BindFunction('sfShape_scale');
      SfmlShapeGetTransform := BindFunction('sfShape_getTransform');
      SfmlShapeGetInverseTransform := BindFunction('sfShape_getInverseTransform');
      SfmlShapeSetTexture := BindFunction('sfShape_setTexture');
      SfmlShapeSetTextureRect := BindFunction('sfShape_setTextureRect');
      SfmlShapeSetFillColor := BindFunction('sfShape_setFillColor');
      SfmlShapeSetOutlineColor := BindFunction('sfShape_setOutlineColor');
      SfmlShapeSetOutlineThickness := BindFunction('sfShape_setOutlineThickness');
      SfmlShapeGetTexture := BindFunction('sfShape_getTexture');
      SfmlShapeGetTextureRect := BindFunction('sfShape_getTextureRect');
      SfmlShapeGetFillColor := BindFunction('sfShape_getFillColor');
      SfmlShapeGetOutlineColor := BindFunction('sfShape_getOutlineColor');
      SfmlShapeGetOutlineThickness := BindFunction('sfShape_getOutlineThickness');
      SfmlShapeGetPointCount := BindFunction('sfShape_getPointCount');
      SfmlShapeGetPoint := BindFunction('sfShape_getPoint');
      SfmlShapeGetLocalBounds := BindFunction('sfShape_getLocalBounds');
      SfmlShapeGetGlobalBounds := BindFunction('sfShape_getGlobalBounds');
      SfmlShapeUpdate := BindFunction('sfShape_update');
      SfmlSpriteCreate := BindFunction('sfSprite_create');
      SfmlSpriteCopy := BindFunction('sfSprite_copy');
      SfmlSpriteDestroy := BindFunction('sfSprite_destroy');
      SfmlSpriteSetPosition := BindFunction('sfSprite_setPosition');
      SfmlSpriteSetRotation := BindFunction('sfSprite_setRotation');
      SfmlSpriteSetScale := BindFunction('sfSprite_setScale');
      SfmlSpriteSetOrigin := BindFunction('sfSprite_setOrigin');
      SfmlSpriteGetPosition := BindFunction('sfSprite_getPosition');
      SfmlSpriteGetRotation := BindFunction('sfSprite_getRotation');
      SfmlSpriteGetScale := BindFunction('sfSprite_getScale');
      SfmlSpriteGetOrigin := BindFunction('sfSprite_getOrigin');
      SfmlSpriteMove := BindFunction('sfSprite_move');
      SfmlSpriteRotate := BindFunction('sfSprite_rotate');
      SfmlSpriteScale := BindFunction('sfSprite_scale');
      SfmlSpriteGetTransform := BindFunction('sfSprite_getTransform');
      SfmlSpriteGetInverseTransform := BindFunction('sfSprite_getInverseTransform');
      SfmlSpriteSetTexture := BindFunction('sfSprite_setTexture');
      SfmlSpriteSetTextureRect := BindFunction('sfSprite_setTextureRect');
      SfmlSpriteSetColor := BindFunction('sfSprite_setColor');
      SfmlSpriteGetTexture := BindFunction('sfSprite_getTexture');
      SfmlSpriteGetTextureRect := BindFunction('sfSprite_getTextureRect');
      SfmlSpriteGetColor := BindFunction('sfSprite_getColor');
      SfmlSpriteGetLocalBounds := BindFunction('sfSprite_getLocalBounds');
      SfmlSpriteGetGlobalBounds := BindFunction('sfSprite_getGlobalBounds');
      SfmlTextCreate := BindFunction('sfText_create');
      SfmlTextCopy := BindFunction('sfText_copy');
      SfmlTextDestroy := BindFunction('sfText_destroy');
      SfmlTextSetPosition := BindFunction('sfText_setPosition');
      SfmlTextSetRotation := BindFunction('sfText_setRotation');
      SfmlTextSetScale := BindFunction('sfText_setScale');
      SfmlTextSetOrigin := BindFunction('sfText_setOrigin');
      SfmlTextGetPosition := BindFunction('sfText_getPosition');
      SfmlTextGetRotation := BindFunction('sfText_getRotation');
      SfmlTextGetScale := BindFunction('sfText_getScale');
      SfmlTextGetOrigin := BindFunction('sfText_getOrigin');
      SfmlTextMove := BindFunction('sfText_move');
      SfmlTextRotate := BindFunction('sfText_rotate');
      SfmlTextScale := BindFunction('sfText_scale');
      SfmlTextGetTransform := BindFunction('sfText_getTransform');
      SfmlTextGetInverseTransform := BindFunction('sfText_getInverseTransform');
      SfmlTextSetString := BindFunction('sfText_setString');
      SfmlTextSetUnicodeString := BindFunction('sfText_setUnicodeString');
      SfmlTextSetFont := BindFunction('sfText_setFont');
      SfmlTextSetCharacterSize := BindFunction('sfText_setCharacterSize');
      SfmlTextSetStyle := BindFunction('sfText_setStyle');
      SfmlTextSetColor := BindFunction('sfText_setColor');
      SfmlTextGetString := BindFunction('sfText_getString');
      SfmlTextGetUnicodeString := BindFunction('sfText_getUnicodeString');
      SfmlTextGetFont := BindFunction('sfText_getFont');
      SfmlTextGetCharacterSize := BindFunction('sfText_getCharacterSize');
      SfmlTextGetStyle := BindFunction('sfText_getStyle');
      SfmlTextGetColor := BindFunction('sfText_getColor');
      SfmlTextFindCharacterPos := BindFunction('sfText_findCharacterPos');
      SfmlTextGetLocalBounds := BindFunction('sfText_getLocalBounds');
      SfmlTextGetGlobalBounds := BindFunction('sfText_getGlobalBounds');
      SfmlTextureCreate := BindFunction('sfTexture_create');
      SfmlTextureCreateFromFile := BindFunction('sfTexture_createFromFile');
      SfmlTextureCreateFromMemory := BindFunction('sfTexture_createFromMemory');
      SfmlTextureCreateFromStream := BindFunction('sfTexture_createFromStream');
      SfmlTextureCreateFromImage := BindFunction('sfTexture_createFromImage');
      SfmlTextureCopy := BindFunction('sfTexture_copy');
      SfmlTextureDestroy := BindFunction('sfTexture_destroy');
      SfmlTextureGetSize := BindFunction('sfTexture_getSize');
      SfmlTextureCopyToImage := BindFunction('sfTexture_copyToImage');
      SfmlTextureUpdateFromPixels := BindFunction('sfTexture_updateFromPixels');
      SfmlTextureUpdateFromImage := BindFunction('sfTexture_updateFromImage');
      SfmlTextureUpdateFromWindow := BindFunction('sfTexture_updateFromWindow');
      SfmlTextureUpdateFromRenderWindow := BindFunction('sfTexture_updateFromRenderWindow');
      SfmlTextureSetSmooth := BindFunction('sfTexture_setSmooth');
      SfmlTextureIsSmooth := BindFunction('sfTexture_isSmooth');
      SfmlTextureSetRepeated := BindFunction('sfTexture_setRepeated');
      SfmlTextureIsRepeated := BindFunction('sfTexture_isRepeated');
      SfmlTextureBind := BindFunction('sfTexture_bind');
      SfmlTextureGetMaximumSize := BindFunction('sfTexture_getMaximumSize');
      SfmlTransformidentity := BindFunction('sfTransform_Identity');
      SfmlTransformFromMatrix := BindFunction('sfTransform_fromMatrix');
      SfmlTransformGetMatrix := BindFunction('sfTransform_getMatrix');
      SfmlTransformGetInverse := BindFunction('sfTransform_getInverse');
      SfmlTransformTransformPoint := BindFunction('sfTransform_transformPoint');
      SfmlTransformTransformRect := BindFunction('sfTransform_transformRect');
      SfmlTransformCombine := BindFunction('sfTransform_combine');
      SfmlTransformTranslate := BindFunction('sfTransform_translate');
      SfmlTransformRotate := BindFunction('sfTransform_rotate');
      SfmlTransformRotateWithCenter := BindFunction('sfTransform_rotateWithCenter');
      SfmlTransformScale := BindFunction('sfTransform_scale');
      SfmlTransformScaleWithCenter := BindFunction('sfTransform_scaleWithCenter');
      SfmlTransformableCreate := BindFunction('sfTransformable_create');
      SfmlTransformableCopy := BindFunction('sfTransformable_copy');
      SfmlTransformableDestroy := BindFunction('sfTransformable_destroy');
      SfmlTransformableSetPosition := BindFunction('sfTransformable_setPosition');
      SfmlTransformableSetRotation := BindFunction('sfTransformable_setRotation');
      SfmlTransformableSetScale := BindFunction('sfTransformable_setScale');
      SfmlTransformableSetOrigin := BindFunction('sfTransformable_setOrigin');
      SfmlTransformableGetPosition := BindFunction('sfTransformable_getPosition');
      SfmlTransformableGetRotation := BindFunction('sfTransformable_getRotation');
      SfmlTransformableGetScale := BindFunction('sfTransformable_getScale');
      SfmlTransformableGetOrigin := BindFunction('sfTransformable_getOrigin');
      SfmlTransformableMove := BindFunction('sfTransformable_move');
      SfmlTransformableRotate := BindFunction('sfTransformable_rotate');
      SfmlTransformableScale := BindFunction('sfTransformable_scale');
      SfmlTransformableGetTransform := BindFunction('sfTransformable_getTransform');
      SfmlTransformableGetInverseTransform := BindFunction('sfTransformable_getInverseTransform');
      SfmlVertexArrayCreate := BindFunction('sfVertexArray_create');
      SfmlVertexArrayCopy := BindFunction('sfVertexArray_copy');
      SfmlVertexArrayDestroy := BindFunction('sfVertexArray_destroy');
      SfmlVertexArrayGetVertexCount := BindFunction('sfVertexArray_getVertexCount');
      SfmlVertexArrayGetVertex := BindFunction('sfVertexArray_getVertex');
      SfmlVertexArrayClear := BindFunction('sfVertexArray_clear');
      SfmlVertexArrayResize := BindFunction('sfVertexArray_resize');
      SfmlVertexArrayAppend := BindFunction('sfVertexArray_append');
      SfmlVertexArraySetPrimitiveType := BindFunction('sfVertexArray_setPrimitiveType');
      SfmlVertexArrayGetPrimitiveType := BindFunction('sfVertexArray_getPrimitiveType');
      SfmlVertexArrayGetBounds := BindFunction('sfVertexArray_getBounds');
      SfmlViewCreate := BindFunction('sfView_create');
      SfmlViewCreateFromRect := BindFunction('sfView_createFromRect');
      SfmlViewCopy := BindFunction('sfView_copy');
      SfmlViewDestroy := BindFunction('sfView_destroy');
      SfmlViewSetCenter := BindFunction('sfView_setCenter');
      SfmlViewSetSize := BindFunction('sfView_setSize');
      SfmlViewSetRotation := BindFunction('sfView_setRotation');
      SfmlViewSetViewport := BindFunction('sfView_setViewport');
      SfmlViewReset := BindFunction('sfView_reset');
      SfmlViewGetCenter := BindFunction('sfView_getCenter');
      SfmlViewGetSize := BindFunction('sfView_getSize');
      SfmlViewGetRotation := BindFunction('sfView_getRotation');
      SfmlViewGetViewport := BindFunction('sfView_getViewport');
      SfmlViewMove := BindFunction('sfView_move');
      SfmlViewRotate := BindFunction('sfView_rotate');
      SfmlViewZoom := BindFunction('sfView_zoom');
    except
      FreeLibrary(CSfmlGraphicsHandle);
      CSfmlGraphicsHandle := 0;
    end;
end;

procedure FreeDLL;
begin
  if CSfmlGraphicsHandle <> 0 then
    FreeLibrary(CSfmlGraphicsHandle);
end;

initialization

InitDLL;

finalization

FreeDLL;

end.
